# Russian translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-12-07 16:23+0100\n"
"PO-Revision-Date: 2019-11-01 10:51+0000\n"
"Last-Translator: Sandro <Unknown>\n"
"Language-Team: Russian <ru@li.org>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2022-12-07 14:36+0000\n"
"X-Generator: Launchpad (build 41e7553f8097ce3a683f90e835708cbe7bf0006c)\n"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Собрать сведения о системе"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Чтобы отправить отчёт о неполадке и собрать сведения о системе, необходимо "
"выполнить аутентификацию"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Отчёты о системных ошибках"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr ""
"Введите свой пароль для доступа к отчётам об ошибках в системных программах"

#: ../apport/ui.py:165
msgid "This package does not seem to be installed correctly"
msgstr "Возможно, этот пакет установлен неправильно"

#: ../apport/ui.py:175
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""
"Похоже, это неофициальный пакет %s. Повторите попытку после обновления "
"индексов доступных пакетов. Если это не помогает, тогда удалите "
"соответствующие сторонние пакеты и попробуйте ещё раз."

#: ../apport/ui.py:205
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"В вашей системе установлены устаревшие версии некоторых пакетов. Обновите "
"следующие пакеты и проверьте, осталась ли проблема:\n"
"\n"
"%s"

#: ../apport/ui.py:359
msgid "unknown program"
msgstr "неизвестная программа"

#: ../apport/ui.py:362
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Извините, программа %s аварийно завершила свою работу"

#: ../apport/ui.py:365 ../apport/ui.py:1899
#, python-format
msgid "Problem in %s"
msgstr "Неполадка в %s"

#: ../apport/ui.py:370
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"В вашем компьютере недостаточно свободной памяти, чтобы автоматически "
"проанализировать неполадку и отправить отчет разработчикам."

#: ../apport/ui.py:430 ../apport/ui.py:448 ../apport/ui.py:621
#: ../apport/ui.py:630 ../apport/ui.py:867 ../apport/ui.py:1677
#: ../apport/ui.py:1860 ../apport/ui.py:1865
msgid "Invalid problem report"
msgstr "Неверный отчёт об ошибке"

#: ../apport/ui.py:431
msgid "You are not allowed to access this problem report."
msgstr "У вас нет доступа к отчёту о неполадке."

#: ../apport/ui.py:439
msgid "Error"
msgstr "Ошибка"

#: ../apport/ui.py:441
msgid "There is not enough disk space available to process this report."
msgstr "Недостаточно места на диске для обработки этого отчёта."

#: ../apport/ui.py:479
msgid "No PID specified"
msgstr "Не указан идентификатор процесса (PID)"

#: ../apport/ui.py:481
msgid "You need to specify a PID. See --help for more information."
msgstr ""
"Необходимо указать идентификатор процесса (PID). Смотрите --help для "
"получения дополнительной информации."

#: ../apport/ui.py:492 ../apport/ui.py:597
msgid "Invalid PID"
msgstr "Неверный PID"

#: ../apport/ui.py:493
msgid "The specified process ID does not exist."
msgstr "Указанный ID процесса не существует."

#: ../apport/ui.py:498
msgid "Not your PID"
msgstr "Не ваш PID"

#: ../apport/ui.py:499
msgid "The specified process ID does not belong to you."
msgstr "Указанный ID процесса не принадлежит вам."

#: ../apport/ui.py:554
msgid "No package specified"
msgstr "Не указан пакет"

#: ../apport/ui.py:556
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Необходимо указать пакет или PID. Запустите программу с ключом --help для "
"получения дополнительной информации."

#: ../apport/ui.py:584
msgid "Permission denied"
msgstr "В доступе отказано"

#: ../apport/ui.py:586
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Указанный процесс запущен другим пользователем. Запустите эту программу с "
"правами владельца процесса или администратора системы."

#: ../apport/ui.py:599
msgid "The specified process ID does not belong to a program."
msgstr "Указанный PID принадлежит другому процессу."

#: ../apport/ui.py:623
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Симптоматический скрипт %s не может определить затронутый пакет"

#: ../apport/ui.py:631
#, python-format
msgid "Package %s does not exist"
msgstr "Пакет %s не существует"

#: ../apport/ui.py:660 ../apport/ui.py:872 ../apport/ui.py:905
#: ../apport/ui.py:915
msgid "Cannot create report"
msgstr "Невозможно создать отчет"

#: ../apport/ui.py:675 ../apport/ui.py:734 ../apport/ui.py:752
msgid "Updating problem report"
msgstr "Обновление отчета о проблеме"

#: ../apport/ui.py:677
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Вы не являетесь отправителем или получателем отчета об этой проблеме, "
"возможно отчет уже существует или уже был закрыт."

#: ../apport/ui.py:689
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Вы не являетесь создателем данного отчета. Намного проще, отметить ошибку "
"как уже существующую, чем создавать свои комментарии и вкладывать их в новую "
"ошибку.\n"
"\n"
"Впоследствии, мы рекомендуем вам подать новое сообщение об ошибке "
"использовании \"ошибка apport\", и сделать замечание об этой ошибке в том же "
"файле.\n"
"\n"
"Вы действительно хотите продолжить?"

#: ../apport/ui.py:735 ../apport/ui.py:753
msgid "No additional information collected."
msgstr "Дополнительная информация не была собрана."

#: ../apport/ui.py:816
msgid "What kind of problem do you want to report?"
msgstr "О какой проблеме вы бы хотели сообщить?"

#: ../apport/ui.py:837
msgid "Unknown symptom"
msgstr "Неизвестный симптом"

#: ../apport/ui.py:838
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Симптом «%s» не известен"

#: ../apport/ui.py:874
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""
"Параметр --window не может быть использован в Wayland.\n"
"\n"
"Найдите идентификатор процесса окна и выполните «ubuntu-bug <идентификатор "
"процесса>».\n"
"\n"
"Идентификатор процесса может быть найден с помощью Системного монитора. "
"Запустите его и найдите интересующее приложение на вкладке Процессы. "
"Идентификатор процесса — номер, указанный в столбце ID."

#: ../apport/ui.py:890
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"После закрытия этого сообщения, пожалуйста, щелкните по окну приложения, "
"чтобы сообщить о проблеме."

#: ../apport/ui.py:907 ../apport/ui.py:916
msgid "xprop failed to determine process ID of the window"
msgstr "xprop не удалось определить ID процесса этого окна"

#: ../apport/ui.py:931
#, python-format
msgid "%(prog)s <report number>"
msgstr "%(prog)s <номер отчёта>"

#: ../apport/ui.py:932
msgid "Specify package name."
msgstr "Задайте имя пакета."

#: ../apport/ui.py:938 ../apport/ui.py:1070
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Добавить дополнительный тег в отчет. Может быть указан несколько раз."

#: ../apport/ui.py:976
#, python-format
msgid ""
"%(prog)s [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%(prog)s [параметры] [симптом|pid|пакет|путь к программе|.apport/.crash файл]"

#: ../apport/ui.py:987
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Запуск в режиме отправки отчёта об ошибке. Требует параметр --package и "
"необязательный --pid, или только --pid. Если параметры не переданы, "
"отображает список известных симптомов. (Применяется, когда передан "
"единственный аргумент.)"

#: ../apport/ui.py:996
msgid "Click a window as a target for filing a problem report."
msgstr "Щелкните по целевому окну для заполнения отчёта о проблеме."

#: ../apport/ui.py:1005
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Запустить в режиме обновления ошибки. Может принимать дополнительный ключ --"
"package."

#: ../apport/ui.py:1014
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Отправить отчёт об ошибке с симптомом. (Применяется, когда название симптома "
"передано в качестве единственного параметра.)"

#: ../apport/ui.py:1023
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Указать имя пакета в режиме --file-bug. Необязательно, если указан --pid. "
"(Применяется, когда имя пакета передано в качестве единственного параметра.)"

#: ../apport/ui.py:1034
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Указывает запущенную программу при работе в режиме --file-bug. При этом "
"отчет будет содержать больше информации. (Подразумевается, что pid — "
"единственный указанный аргумент.)"

#: ../apport/ui.py:1042
msgid "The provided pid is a hanging application."
msgstr "Указанный идентификатор принадлежит процессу, который не отвечает."

#: ../apport/ui.py:1050
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Отправить данные о сбое из заданного файла .apport или .crash вместо "
"ожидаемых в %s. (Применяется, когда файл передан в качестве единственного "
"параметра.)"

#: ../apport/ui.py:1060
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"При работе в режиме отправки отчета, сохраняет информацию в файле вместо ее "
"отправки. Этот файл можно будет отправить позднее или с другого компьютера."

#: ../apport/ui.py:1078
msgid "Print the Apport version number."
msgstr "Напечатать номер версии Apport."

#: ../apport/ui.py:1240
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Будет произведён запуск «apport-retrace» в окне терминала для выполнения "
"проверки аварийного завершения работы."

#: ../apport/ui.py:1244
msgid "Run gdb session"
msgstr "Запустить сеанс gdb"

#: ../apport/ui.py:1245
msgid "Run gdb session without downloading debug symbols"
msgstr "Запустить сеанс gdb, не выполняя загрузку отладочных символов"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1247
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Обновить %s с полным отслеживанием символического стека"

#: ../apport/ui.py:1309
msgid "Can't remember send report status settings"
msgstr "Не удаётся запомнить настройки статуса отправки отчёта"

#: ../apport/ui.py:1313
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""
"Не удалось сохранить состояние отчета о сбое. Не удается установить режим "
"авто или никогда."

#: ../apport/ui.py:1396 ../apport/ui.py:1409
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Этот отчет о проблеме относится к программе, которая не установлена."

#: ../apport/ui.py:1433
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Неполадка произошла с программой %s, в которую были внесены изменения с "
"момента её аварийного завершения работы."

#: ../apport/ui.py:1494 ../apport/ui.py:1618 ../apport/ui.py:1869
msgid "This problem report is damaged and cannot be processed."
msgstr "Этот отчёт о неполадке повреждён и не может быть обработан."

#: ../apport/ui.py:1503
msgid "This report is about a package that is not installed."
msgstr "Это отчёт о пакете, который не установлен."

#: ../apport/ui.py:1511
msgid "An error occurred while attempting to process this problem report:"
msgstr "Произошла ошибка при попытке обработать это сообщение о неполадке:"

#: ../apport/ui.py:1528
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""
"У вас установлено две версии этого приложения. Об ошибке в какой из них вы "
"хотите сообщить?"

#: ../apport/ui.py:1533
#, python-format
msgid "%s snap"
msgstr "%s snap-пакет"

#: ../apport/ui.py:1534
#, python-format
msgid "%s deb package"
msgstr "%s deb-пакет"

#: ../apport/ui.py:1575
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""
"%s предоставлен в виде snap-пакета и опубликован %s. Для получения помощи "
"свяжитесь с ними по %s."

#: ../apport/ui.py:1580
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""
"%s предоставлен в виде snap-пакета и опубликован %s. Контактный адрес не "
"указан. Для получения помощи посетите форум https://forum.snapcraft.io/."

#: ../apport/ui.py:1679
msgid "Could not determine the package or source package name."
msgstr "Не удалось определить имя пакета или имя пакета с исходным кодом."

#: ../apport/ui.py:1704
msgid "Unable to start web browser"
msgstr "Не удалось запустить веб-браузер"

#: ../apport/ui.py:1705
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Не удалось запустить веб-браузер, чтобы открыть %s."

#: ../apport/ui.py:1815
msgid "Network problem"
msgstr "Неполадка с сетью"

#: ../apport/ui.py:1819
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Не удается подключиться к базе данных по сбоям, пожалуйста, проверьте "
"подключение к Интернету."

#: ../apport/ui.py:1851
msgid "Memory exhaustion"
msgstr "Недостаток памяти"

#: ../apport/ui.py:1853
msgid "Your system does not have enough memory to process this crash report."
msgstr "В системе недостаточно памяти для обработки этого отчёта об ошибке."

#: ../apport/ui.py:1904
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Не удаётся сообщить о неполадке:\n"
"\n"
"%s"

#: ../apport/ui.py:1960 ../apport/ui.py:1972
msgid "Problem already known"
msgstr "О неполадке уже известно"

#: ../apport/ui.py:1962
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Об этой неполадке уже известно. Существующий отчёт о ней открыт в вашем "
"браузере. Пожалуйста, проверьте, можете ли вы добавить в него иную полезную "
"информацию, которая могла бы помочь разработчикам."

#: ../apport/ui.py:1974
msgid "This problem was already reported to developers. Thank you!"
msgstr "Сообщение о неисправности отправлено разработчикам. Спасибо за помощь!"

#: ../bin/apport-cli.py:84
msgid "Press any key to continue..."
msgstr "Чтобы продолжить, нажмите любую клавишу..."

#: ../bin/apport-cli.py:91
msgid "What would you like to do? Your options are:"
msgstr "Что вы хотите сделать? Возможные варианты:"

#: ../bin/apport-cli.py:104
#, python-format
msgid "Please choose (%s):"
msgstr "Пожалуйста, выберите (%s):"

#: ../bin/apport-cli.py:172
#, python-format
msgid "(%i bytes)"
msgstr "(%i байт)"

#: ../bin/apport-cli.py:174 ../gtk/apport-gtk.py:169 ../kde/apport-kde.py:406
msgid "(binary data)"
msgstr "(двоичные данные)"

#: ../bin/apport-cli.py:209 ../gtk/apport-gtk.py:208 ../gtk/apport-gtk.ui.h:6
#: ../kde/apport-kde.py:199
msgid "Send problem report to the developers?"
msgstr "Отправить отчёт об ошибке разработчикам?"

#: ../bin/apport-cli.py:211
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"После того, как отчёт будет отправлен, заполните форму\n"
"в автоматически открывшемся окне браузера."

#: ../bin/apport-cli.py:218
#, python-format
msgid "&Send report (%s)"
msgstr "&Отправить отчёт (%s)"

#: ../bin/apport-cli.py:223
msgid "&Examine locally"
msgstr "&Локальная проверка"

#: ../bin/apport-cli.py:227
msgid "&View report"
msgstr "&Просмотреть отчёт"

#: ../bin/apport-cli.py:230
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Сохранить файл отчёта для последующей отправки или копирования куда-либо"

#: ../bin/apport-cli.py:235
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Отменить и &игнорировать будущие сбои в этой версии программы"

#: ../bin/apport-cli.py:238 ../bin/apport-cli.py:332 ../bin/apport-cli.py:366
#: ../bin/apport-cli.py:389
msgid "&Cancel"
msgstr "О&тменить"

#: ../bin/apport-cli.py:273
msgid "Problem report file:"
msgstr "Файл отчёта о проблеме:"

#: ../bin/apport-cli.py:279 ../bin/apport-cli.py:284
msgid "&Confirm"
msgstr "&Подтвердить"

#: ../bin/apport-cli.py:283
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"

#: ../bin/apport-cli.py:289 ../kde/apport-kde.py:462
msgid "Collecting problem information"
msgstr "Сбор информации о проблеме"

#: ../bin/apport-cli.py:291
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Собранная информация может быть направлена разработчикам\n"
"для улучшения приложения. Это может занять несколько минут."

#: ../bin/apport-cli.py:307 ../gtk/apport-gtk.ui.h:17 ../kde/apport-kde.py:511
msgid "Uploading problem information"
msgstr "Передача информации о неполадке"

#: ../bin/apport-cli.py:309
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Собранная информация направляется в систему отслеживания ошибок.\n"
"Это может занять несколько минут."

#: ../bin/apport-cli.py:365
msgid "&Done"
msgstr "&Готово"

#: ../bin/apport-cli.py:371
msgid "none"
msgstr "пусто"

#: ../bin/apport-cli.py:373
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Выбрано: %s. Несколько вариантов:"

#: ../bin/apport-cli.py:390
msgid "Choices:"
msgstr "Выбор:"

#: ../bin/apport-cli.py:404
msgid "Path to file (Enter to cancel):"
msgstr "Путь к файлу (Enter — отмена):"

#: ../bin/apport-cli.py:410
msgid "File does not exist."
msgstr "Файл не существует."

#: ../bin/apport-cli.py:412
msgid "This is a directory."
msgstr "Это — директория."

#: ../bin/apport-cli.py:418
msgid "To continue, you must visit the following URL:"
msgstr "Чтобы продолжить, вы должны пройти по следующему адресу:"

#: ../bin/apport-cli.py:421
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Теперь вы можете открыть браузер или скопировать URL в браузер на другой "
"компьютер."

#: ../bin/apport-cli.py:427
msgid "Launch a browser now"
msgstr "Запустить браузер"

#: ../bin/apport-cli.py:443
msgid "No pending crash reports. Try --help for more information."
msgstr "Нет ожидающих сообщений о сбоях. Попробуйте ключ --help."

#: ../bin/apport-retrace.py:44
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Не добавлять новые трассировки в отчет, а посылать на стандартный вывод."

#: ../bin/apport-retrace.py:53
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Запустить интерактивный сеанс gdb с дампом ядра из отчёта (-o игнорируется; "
"отчёт не перезаписывается)"

#: ../bin/apport-retrace.py:62
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Сохранить измененный отчет в файл вместо изменения оригинального отчета"

#: ../bin/apport-retrace.py:72
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Удалить дамп ядра из отчёта после восстановления трассировки стека"

#: ../bin/apport-retrace.py:80
msgid "Override report's CoreFile"
msgstr "Заменить CoreFile в отчёте"

#: ../bin/apport-retrace.py:86
msgid "Override report's ExecutablePath"
msgstr "Заменить ExecutablePath в отчёте"

#: ../bin/apport-retrace.py:92
msgid "Override report's ProcMaps"
msgstr "Заменить ProcMaps в отчёте"

#: ../bin/apport-retrace.py:98
msgid "Rebuild report's Package information"
msgstr "Заново построить информацию о пакетах в отчёте"

#: ../bin/apport-retrace.py:105
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Создать временную среду, затем загрузить/установить в неё необходимые пакеты "
"и отладочные символы; без этого параметра предполагается, что необходимые "
"пакеты и отладочные символы в системе уже установлены. Аргумент указывает на "
"базовую папку конфигурации системы пакетов; если вы указали \"system\", "
"будут использоваться системные файлы конфигурации, но только в случае "
"обнаружения аварийных ситуаций, произошедших в выпуске системы, работающем в "
"данный момент."

#: ../bin/apport-retrace.py:119
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""
"Создать ещё одну временную изолированную среду для установки gdb и его "
"зависимостей, используя вместо установленной у вас версии gdb выпуск, "
"совпадающий с отчётом."

#: ../bin/apport-retrace.py:129
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""
"Сообщать о ходе выполнения загрузки/установки пакетов во временную среду"

#: ../bin/apport-retrace.py:136
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"Добавлять временные отметки до сообщений в журнале, для групповых операций"

#: ../bin/apport-retrace.py:142
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Создавать и использовать сторонние репозитории из источников, указанных в "
"отчётах"

#: ../bin/apport-retrace.py:150
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Папка для сохранения пакетов, загружаемых во временную среду"

#: ../bin/apport-retrace.py:156
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Директория для распаковки пакетов. При последующих запусках все уже "
"загруженные пакеты будут распаковываться в это изолированное окружение."

#: ../bin/apport-retrace.py:167 ../bin/apport-valgrind.py:97
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"Установить во временную среду дополнительный пакет (может указываться "
"несколько раз)"

#: ../bin/apport-retrace.py:174
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Путь к файлу с информацией о проверке подлинности базы сбоев. Используется "
"при указании ID сбоя для отправки трассировок стека (только когда -g, -o или "
"-s не указаны)"

#: ../bin/apport-retrace.py:184
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Отобразить трассировки и запросить подтверждение перед их отправкой в базу "
"данных сбоев."

#: ../bin/apport-retrace.py:192
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Путь к дублирующей базе данных sqlite (по умолчанию: без проверки дубликатов)"

#: ../bin/apport-retrace.py:200
msgid "Do not add StacktraceSource to the report."
msgstr "Не прилагать StacktraceSource к отчёту."

#: ../bin/apport-retrace.py:213
msgid "You cannot use -C without -S. Stopping."
msgstr "Нельзя использовать -C без -S. Остановка."

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:243
msgid "OK to send these as attachments? [y/n]"
msgstr "Отправить эти приложения? [y/n]"

#: ../bin/apport-unpack.py:29
#, python-format
msgid "%(prog)s <report> <target directory>"
msgstr "%(prog)s <отчёт> <целевой каталог>"

#: ../bin/apport-unpack.py:31
msgid "Report file to unpack"
msgstr "Файл отчёта для распаковки."

#: ../bin/apport-unpack.py:33
msgid "directory to unpack report to"
msgstr "Каталог для распаковки отчёта."

#: ../bin/apport-unpack.py:59
msgid "Destination directory exists and is not empty."
msgstr "Папка назначения существует и не пуста."

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Смотрите подробности в man-странице."

#: ../bin/apport-valgrind.py:46
msgid "specify the log file name produced by valgrind"
msgstr "укажите имя log-файла для valgrind"

#: ../bin/apport-valgrind.py:52
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"использовать ранее созданный каталог песочницы (SDIR) или создать его если "
"он не существует"

#: ../bin/apport-valgrind.py:60
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"не создавать и не использовать каталог песочницы для дополнительных символов "
"отладки, а полагаться лишь на установленные символы отладки."

#: ../bin/apport-valgrind.py:69
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"использовать ранее созданный каталог кэша (CDIR) или создать его если он не "
"существует"

#: ../bin/apport-valgrind.py:78
msgid "report download/install progress when installing packages into sandbox"
msgstr ""
"показывать прогресс загрузки/установки во время установки пакетов в песочницу"

#: ../bin/apport-valgrind.py:86
msgid ""
"the executable that is run under valgrind's memcheck tool for memory leak "
"detection"
msgstr ""
"Исполняемый файл, который запускается с помощью инструмента Valgrind "
"memcheck для обнаружения утечки памяти."

#: ../bin/apport-valgrind.py:129
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Ошибка: %s — не исполняемый файл. Остановка."

#: ../data/apportcheckresume.py:68
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Это произошло во время предыдущего ждущего режима, что не даёт системе "
"правильно выйти из него."

#: ../data/apportcheckresume.py:73
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Это произошло во время предыдущего спящего режима, что не даёт системе "
"правильно выйти из него."

#: ../data/apportcheckresume.py:81
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Процесс создания отчёта завис очень близко к завершению; для нормального "
"завершения он должен был появиться."

#: ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr "Система может стать нестабильной, возможно потребуется перезагрузка."

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr "Сообщить о неполадке..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Сообщить о недоработке разработчикам"

#: ../gtk/apport-gtk.py:185
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Извините, приложение %s внезапно завершилось."

#: ../gtk/apport-gtk.py:188
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Извините, %s было непредвиденно закрыто."

#: ../gtk/apport-gtk.py:193 ../kde/apport-kde.py:214 ../kde/apport-kde.py:266
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Извините, возникла внутренняя ошибка %s."

#: ../gtk/apport-gtk.py:216 ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:207
msgid "Send"
msgstr "Отправить"

#: ../gtk/apport-gtk.py:234 ../gtk/apport-gtk.py:666 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:330
msgid "Show Details"
msgstr "Показать подробности"

#: ../gtk/apport-gtk.py:247 ../kde/apport-kde.py:258 ../kde/apport-kde.py:276
msgid "Continue"
msgstr "Продолжить"

#: ../gtk/apport-gtk.py:271
#, python-format
msgid "The application %s has stopped responding."
msgstr "Приложение «%s» перестало отвечать."

#: ../gtk/apport-gtk.py:275
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Программа «%s» перестала отвечать."

#: ../gtk/apport-gtk.py:292 ../kde/apport-kde.py:222
#, python-format
msgid "Package: %s"
msgstr "Пакет: %s"

#: ../gtk/apport-gtk.py:298 ../kde/apport-kde.py:229
msgid "Sorry, a problem occurred while installing software."
msgstr ""
"Извините, обнаружена неполадка во время установки программного обеспечения."

#: ../gtk/apport-gtk.py:310 ../gtk/apport-gtk.py:334 ../kde/apport-kde.py:238
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "В приложении %s произошла внутренняя ошибка."

#: ../gtk/apport-gtk.py:316 ../kde/apport-kde.py:245
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Приложение %s внезапно закрылось."

#: ../gtk/apport-gtk.py:347 ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:271
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"При возникновении этой неполадки в дальнейшем попробуйте перезапустить "
"компьютер."

#: ../gtk/apport-gtk.py:352 ../kde/apport-kde.py:278
msgid "Ignore future problems of this type"
msgstr "Игнорировать этот тип неполадок в дальнейшем"

#: ../gtk/apport-gtk.py:670 ../kde/apport-kde.py:327
msgid "Hide Details"
msgstr "Скрыть подробности"

#: ../gtk/apport-gtk.ui.h:1 ../kde/apport-kde.py:552 ../kde/apport-kde.py:595
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Отмена"

#: ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "OK"

#: ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Отчёт о неполадке"

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Извините, возникла внутренняя ошибка.</b></big>"

#: ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "Запомнить на будущее"

#: ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Игнорировать будущие сбои в этой версии программы"

#: ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "Перезапустить это приложение"

#: ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Локальная проверка"

#: ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "Не отправлять"

#: ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Сбор информации о неполадке</b></big>"

#: ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Производится сбор информации, которая может помочь разработчикам исправить "
"эту ошибку."

#: ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Передача сведений о неполадке</b></big>"

#: ../gtk/apport-gtk.ui.h:19 ../kde/apport-kde.py:513
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Собранные данные пересылаются в систему учёта ошибок. Это может занять "
"несколько минут."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Файл отчета Apport"

#: ../kde/apport-kde.py:261
msgid "Leave Closed"
msgstr "Оставить закрытым"

#: ../kde/apport-kde.py:262 ../kde/apport-kde.py:432
msgid "Relaunch"
msgstr "Перезапустить"

#: ../kde/apport-kde.py:355
msgid "Username:"
msgstr "Имя пользователя:"

#: ../kde/apport-kde.py:356
msgid "Password:"
msgstr "Пароль:"

#: ../kde/apport-kde.py:461
msgid "Collecting Problem Information"
msgstr "Сбор информации о неполадке"

#: ../kde/apport-kde.py:464
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Собранную информацию можно отправить разработчикам чтобы улучшить "
"приложение. Это может занять несколько минут."

#: ../kde/apport-kde.py:510
msgid "Uploading Problem Information"
msgstr "Передача информации о неполадке"
