# translation of ta(3).po to tamil
# Tamil translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
#
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
# drtvasudevan <agnihot3@gmail.com>, 2006.
msgid ""
msgstr ""
"Project-Id-Version: ta(3)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-06-13 16:28+0200\n"
"PO-Revision-Date: 2012-03-10 22:25+0000\n"
"Last-Translator: Sarrvesh <sarrfriend@gmail.com>\n"
"Language-Team: tamil <Ubuntu-l10n-tam@lists.ubuntu.com>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2022-08-19 12:20+0000\n"
"X-Generator: Launchpad (build 87919ae1fbf1142b0e02b80650e6ccf3e775beb3)\n"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr ""

#: ../apport/ui.py:259
msgid "This package does not seem to be installed correctly"
msgstr ""

#: ../apport/ui.py:269
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""

#: ../apport/ui.py:299
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:450
msgid "unknown program"
msgstr ""

#: ../apport/ui.py:452
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../apport/ui.py:454
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"தங்கள் கணிப்பொறியில் தேவையான இடம் இல்லாததால் மென்பொருட்களை ஆராய்ந்து பிரச்சனைகளை "
"தெரிவிக்க இயலவில்லை"

#: ../apport/ui.py:459 ../apport/ui.py:1862
#, python-format
msgid "Problem in %s"
msgstr "%s இல் இடர்பாடு"

#: ../apport/ui.py:515 ../apport/ui.py:532 ../apport/ui.py:698
#: ../apport/ui.py:704 ../apport/ui.py:927 ../apport/ui.py:1689
#: ../apport/ui.py:1829 ../apport/ui.py:1835
msgid "Invalid problem report"
msgstr ""

#: ../apport/ui.py:516
msgid "You are not allowed to access this problem report."
msgstr "இந்தப்  பிழை அறிக்கையை அணுக தங்களுக்கு அனுமதி கிடையாது"

#: ../apport/ui.py:524
msgid "Error"
msgstr "பிழை"

#: ../apport/ui.py:526
msgid "There is not enough disk space available to process this report."
msgstr "இப் பிழை அறிக்கையைக் கையாள போதிய இடம் தங்கள் கணிப்பொறியில் இல்லை."

#: ../apport/ui.py:562
msgid "No PID specified"
msgstr ""

#: ../apport/ui.py:563
msgid "You need to specify a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:572 ../apport/ui.py:677
msgid "Invalid PID"
msgstr ""

#: ../apport/ui.py:572
msgid "The specified process ID does not exist."
msgstr ""

#: ../apport/ui.py:577
msgid "Not your PID"
msgstr ""

#: ../apport/ui.py:578
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../apport/ui.py:635
msgid "No package specified"
msgstr ""

#: ../apport/ui.py:637
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:664
msgid "Permission denied"
msgstr "அனுமதி மறுக்கப்பட்டது"

#: ../apport/ui.py:666
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""

#: ../apport/ui.py:678
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../apport/ui.py:699
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../apport/ui.py:705
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../apport/ui.py:734 ../apport/ui.py:932 ../apport/ui.py:965
#: ../apport/ui.py:972
msgid "Cannot create report"
msgstr "அறிக்கையை உருவாக்க இயலவில்லை"

#: ../apport/ui.py:749 ../apport/ui.py:803 ../apport/ui.py:820
msgid "Updating problem report"
msgstr ""

#: ../apport/ui.py:751
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../apport/ui.py:763
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""

#: ../apport/ui.py:803 ../apport/ui.py:820
msgid "No additional information collected."
msgstr ""

#: ../apport/ui.py:876
msgid "What kind of problem do you want to report?"
msgstr "எத்தகையப் பிழையை அறிவிக்க விரும்புகிறீர்கள்?"

#: ../apport/ui.py:895
msgid "Unknown symptom"
msgstr ""

#: ../apport/ui.py:896
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../apport/ui.py:934
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""

#: ../apport/ui.py:950
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""

#: ../apport/ui.py:966 ../apport/ui.py:973
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../apport/ui.py:988
#, python-format
msgid "%(prog)s <report number>"
msgstr ""

#: ../apport/ui.py:989
msgid "Specify package name."
msgstr ""

#: ../apport/ui.py:995 ../apport/ui.py:1123
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../apport/ui.py:1031
#, python-format
msgid ""
"%(prog)s [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:1042
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../apport/ui.py:1051
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../apport/ui.py:1059
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../apport/ui.py:1067
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:1076
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../apport/ui.py:1087
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:1095
msgid "The provided pid is a hanging application."
msgstr ""

#: ../apport/ui.py:1103
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../apport/ui.py:1113
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../apport/ui.py:1129
msgid "Print the Apport version number."
msgstr ""

#: ../apport/ui.py:1290
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../apport/ui.py:1294
msgid "Run gdb session"
msgstr ""

#: ../apport/ui.py:1295
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1297
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../apport/ui.py:1351
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../apport/ui.py:1355
msgid "Can't remember send report status settings"
msgstr ""

#: ../apport/ui.py:1433 ../apport/ui.py:1446
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""

#: ../apport/ui.py:1466
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#. can happen with broken core dumps
#. can happen with broken gz values
#: ../apport/ui.py:1525 ../apport/ui.py:1637 ../apport/ui.py:1833
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#: ../apport/ui.py:1531
msgid "This report is about a package that is not installed."
msgstr ""

#: ../apport/ui.py:1538
msgid "An error occurred while attempting to process this problem report:"
msgstr "இந்தப்  பிழை அறிக்கையைக்  கையாளும்போது  பிழை ஏற்பட்டுள்ளது"

#: ../apport/ui.py:1555
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""

#: ../apport/ui.py:1560
#, python-format
msgid "%s snap"
msgstr ""

#: ../apport/ui.py:1561
#, python-format
msgid "%s deb package"
msgstr ""

#: ../apport/ui.py:1599
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../apport/ui.py:1604
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../apport/ui.py:1690
msgid "Could not determine the package or source package name."
msgstr "பொதிகளின் அல்லது மூல தொகுப்புகளின் பெயரை நிர்ணயிக்க முடியவில்லை."

#: ../apport/ui.py:1721
msgid "Unable to start web browser"
msgstr ""

#: ../apport/ui.py:1722
#, python-format
msgid "Unable to start web browser to open %s."
msgstr ""

#: ../apport/ui.py:1791
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../apport/ui.py:1794
msgid "Network problem"
msgstr ""

#: ../apport/ui.py:1820
msgid "Memory exhaustion"
msgstr ""

#: ../apport/ui.py:1822
msgid "Your system does not have enough memory to process this crash report."
msgstr ""

#: ../apport/ui.py:1867
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:1921 ../apport/ui.py:1933
msgid "Problem already known"
msgstr ""

#: ../apport/ui.py:1923
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""

#: ../apport/ui.py:1934
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../bin/apport-cli.py:87
msgid "Press any key to continue..."
msgstr ""

#: ../bin/apport-cli.py:94
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../bin/apport-cli.py:107
#, python-format
msgid "Please choose (%s):"
msgstr ""

#: ../bin/apport-cli.py:167
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../bin/apport-cli.py:169 ../gtk/apport-gtk.py:138 ../kde/apport-kde.py:414
msgid "(binary data)"
msgstr ""

#: ../bin/apport-cli.py:209 ../gtk/apport-gtk.ui.h:6 ../kde/apport-kde.py:205
msgid "Send problem report to the developers?"
msgstr ""

#: ../bin/apport-cli.py:211
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""

#: ../bin/apport-cli.py:218
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../bin/apport-cli.py:222
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:226
msgid "&View report"
msgstr ""

#: ../bin/apport-cli.py:228
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""

#: ../bin/apport-cli.py:231
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""

#: ../bin/apport-cli.py:234 ../bin/apport-cli.py:314 ../bin/apport-cli.py:348
#: ../bin/apport-cli.py:369
msgid "&Cancel"
msgstr ""

#: ../bin/apport-cli.py:255
msgid "Problem report file:"
msgstr ""

#: ../bin/apport-cli.py:261 ../bin/apport-cli.py:266
msgid "&Confirm"
msgstr ""

#: ../bin/apport-cli.py:265
#, python-format
msgid "Error: %s"
msgstr ""

#: ../bin/apport-cli.py:271 ../kde/apport-kde.py:462
msgid "Collecting problem information"
msgstr ""

#: ../bin/apport-cli.py:273
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""

#: ../bin/apport-cli.py:289 ../gtk/apport-gtk.ui.h:17 ../kde/apport-kde.py:512
msgid "Uploading problem information"
msgstr "பிரச்னையின் தகவலைப் பதிவேற்றப்படுகிறது"

#: ../bin/apport-cli.py:291
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""

#: ../bin/apport-cli.py:347
msgid "&Done"
msgstr ""

#: ../bin/apport-cli.py:353
msgid "none"
msgstr ""

#: ../bin/apport-cli.py:354
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../bin/apport-cli.py:370
msgid "Choices:"
msgstr ""

#: ../bin/apport-cli.py:384
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../bin/apport-cli.py:390
msgid "File does not exist."
msgstr ""

#: ../bin/apport-cli.py:392
msgid "This is a directory."
msgstr ""

#: ../bin/apport-cli.py:397
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../bin/apport-cli.py:399
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""

#: ../bin/apport-cli.py:404
msgid "Launch a browser now"
msgstr ""

#: ../bin/apport-cli.py:419
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../bin/apport-retrace.py:48
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:55
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:64
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:73
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:76
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:79
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:82
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:88
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:95
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:109
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""

#: ../bin/apport-retrace.py:119
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:125
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:131
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""

#: ../bin/apport-retrace.py:139
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:145
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-retrace.py:156 ../bin/apport-valgrind.py:99
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:163
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:173
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:181
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:188
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../bin/apport-retrace.py:201
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:231
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../bin/apport-unpack.py:35
#, python-format
msgid "%(prog)s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:36
msgid "Report file to unpack"
msgstr ""

#: ../bin/apport-unpack.py:37
msgid "directory to unpack report to"
msgstr ""

#: ../bin/apport-unpack.py:86
msgid "Destination directory exists and is not empty."
msgstr ""

#: ../bin/apport-valgrind.py:40
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:49
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:55
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:63
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:72
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:81
msgid "report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:88
msgid ""
"the executable that is run under valgrind's memcheck tool for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:130
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../data/apportcheckresume.py:75
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""

#: ../data/apportcheckresume.py:80
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""

#: ../data/apportcheckresume.py:88
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../data/kernel_oops.py:33
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr ""

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../gtk/apport-gtk.py:155
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:158
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:163 ../kde/apport-kde.py:220 ../kde/apport-kde.py:269
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../gtk/apport-gtk.py:186 ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:213
msgid "Send"
msgstr ""

#: ../gtk/apport-gtk.py:207 ../gtk/apport-gtk.py:613 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:330
msgid "Show Details"
msgstr ""

#: ../gtk/apport-gtk.py:220 ../kde/apport-kde.py:261 ../kde/apport-kde.py:276
msgid "Continue"
msgstr ""

#: ../gtk/apport-gtk.py:244
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../gtk/apport-gtk.py:248
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../gtk/apport-gtk.py:265 ../kde/apport-kde.py:228
#, python-format
msgid "Package: %s"
msgstr ""

#: ../gtk/apport-gtk.py:271 ../kde/apport-kde.py:235
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../gtk/apport-gtk.py:281 ../gtk/apport-gtk.py:300 ../kde/apport-kde.py:243
#, python-format
msgid "The application %s has experienced an internal error."
msgstr ""

#: ../gtk/apport-gtk.py:283 ../kde/apport-kde.py:248
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:308 ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:273
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../gtk/apport-gtk.py:311 ../kde/apport-kde.py:278
msgid "Ignore future problems of this type"
msgstr ""

#: ../gtk/apport-gtk.py:617 ../kde/apport-kde.py:327
msgid "Hide Details"
msgstr ""

#: ../gtk/apport-gtk.ui.h:1 ../kde/apport-kde.py:381 ../kde/apport-kde.py:551
msgid "Apport"
msgstr "அப்போர்ட்"

#: ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr ""

#: ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr ""

#: ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr ""

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr ""

#: ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""

#: ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:19 ../kde/apport-kde.py:514
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../kde/apport-kde.py:264
msgid "Leave Closed"
msgstr ""

#: ../kde/apport-kde.py:265 ../kde/apport-kde.py:432
msgid "Relaunch"
msgstr ""

#: ../kde/apport-kde.py:358
msgid "Username:"
msgstr "பயனாளர் பெயர்:"

#: ../kde/apport-kde.py:361
msgid "Password:"
msgstr "கடவுச் சொல்:"

#: ../kde/apport-kde.py:461
msgid "Collecting Problem Information"
msgstr ""

#: ../kde/apport-kde.py:464
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""

#: ../kde/apport-kde.py:511
msgid "Uploading Problem Information"
msgstr "பிரச்னையின் தகவலைப் பதிவேற்றப்படுகிறது"
