# Turkish translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-12-07 16:21+0100\n"
"PO-Revision-Date: 2015-04-27 21:47+0000\n"
"Last-Translator: Martin Pitt <martin@piware.de>\n"
"Language-Team: Turkish <tr@li.org>\n"
"Language: tr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2022-08-19 12:20+0000\n"
"X-Generator: Launchpad (build 87919ae1fbf1142b0e02b80650e6ccf3e775beb3)\n"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Sistem bilgisi topla"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Bu sorun raporu için sistem bilgisi toplamada yetkilendirme gereklidir."

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Sistem problem raporları"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr ""
"Lütfen sistem programlarının problem raporlarına ulaşmak için şifrenizi girin"

#: ../apport/ui.py:165
msgid "This package does not seem to be installed correctly"
msgstr "Bu paket doğru yüklenmiş gibi görünmüyor."

#: ../apport/ui.py:175
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""

#: ../apport/ui.py:205
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Kurulmuş eski paket sürümlerine sahipsiniz. Lütfen aşağıdaki paketleri "
"yükseltin ve ardından sorunun yine ortaya çıkıp çıkmadığını kontrol edin.\n"
"\n"
"%s"

#: ../apport/ui.py:359
msgid "unknown program"
msgstr "bilinmeyen program"

#: ../apport/ui.py:362
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Üzgünüm, \"%s\" programı beklenmedik şekilde kapandı"

#: ../apport/ui.py:365 ../apport/ui.py:1899
#, python-format
msgid "Problem in %s"
msgstr "%s'de problem"

#: ../apport/ui.py:370
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Bilgisayarınız otomatik olarak sorunu analiz etmek ve geliştiricilere rapor "
"göndermek için yeterli boş belleğe sahip değil."

#: ../apport/ui.py:430 ../apport/ui.py:448 ../apport/ui.py:621
#: ../apport/ui.py:630 ../apport/ui.py:867 ../apport/ui.py:1677
#: ../apport/ui.py:1860 ../apport/ui.py:1865
msgid "Invalid problem report"
msgstr "Geçersiz sorun raporu"

#: ../apport/ui.py:431
msgid "You are not allowed to access this problem report."
msgstr "Bu hata raporuna erişmeye izniniz yok."

#: ../apport/ui.py:439
msgid "Error"
msgstr "Hata"

#: ../apport/ui.py:441
msgid "There is not enough disk space available to process this report."
msgstr "Bu raporu işlemek için yeterli disk alanı yok."

#: ../apport/ui.py:479
msgid "No PID specified"
msgstr ""

#: ../apport/ui.py:481
msgid "You need to specify a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:492 ../apport/ui.py:597
msgid "Invalid PID"
msgstr "Geçersiz PID"

#: ../apport/ui.py:493
msgid "The specified process ID does not exist."
msgstr ""

#: ../apport/ui.py:498
msgid "Not your PID"
msgstr ""

#: ../apport/ui.py:499
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../apport/ui.py:554
msgid "No package specified"
msgstr "Hiçbir paket belirtilmemiş"

#: ../apport/ui.py:556
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Bir paket veya PID belirtmelisiniz. Daha fazla bilgi için --help çıktısına "
"bakın."

#: ../apport/ui.py:584
msgid "Permission denied"
msgstr "İzin verilmedi"

#: ../apport/ui.py:586
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Belirtilen süreç size ait değil. Lütfen bu programı süreç sahibi veya root "
"olarak çalıştırın."

#: ../apport/ui.py:599
msgid "The specified process ID does not belong to a program."
msgstr "Belirlenen işlem ID'si bir programa ait değil."

#: ../apport/ui.py:623
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Symptom betiği %s etkin bir paket tanımlamadı"

#: ../apport/ui.py:631
#, python-format
msgid "Package %s does not exist"
msgstr "%s pakedi bulunamadı"

#: ../apport/ui.py:660 ../apport/ui.py:872 ../apport/ui.py:905
#: ../apport/ui.py:915
msgid "Cannot create report"
msgstr "Rapor oluşturulamıyor"

#: ../apport/ui.py:675 ../apport/ui.py:734 ../apport/ui.py:752
msgid "Updating problem report"
msgstr "Sorun raporu güncelleniyor"

#: ../apport/ui.py:677
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Bu problem raporunun bildireni ya da takipçisi değilsiniz. ya da rapor çift "
"kopya veya halihazırda kapandı.\n"
"\n"
"Lütfen ''apport-bug'' kullanarak yeni bir rapor oluşturun."

#: ../apport/ui.py:689
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Bu problem raporunun bildireni değilsiniz. Yorumlarınızı ve eklentilerinizi "
"yeni bir hataya taşımaktansa bir hatayı bir diğerinin kopyası olarak "
"işaretlemek çok daha kolaydır.\n"
"\n"
"Daha sonra size: ''apport-bug'' kullanarak yeni bir hata raporu "
"oluşturmanızı ve oluşturduğunuz bu hata ile ilgili bir yorum yapmanızı "
"öneriyoruz.\n"
"\n"
"Gerçekten devam etmek istiyor musunuz?"

#: ../apport/ui.py:735 ../apport/ui.py:753
msgid "No additional information collected."
msgstr "Hiçbir ek bilgi toplanmadı."

#: ../apport/ui.py:816
msgid "What kind of problem do you want to report?"
msgstr "Ne tür bir sorun bildirmek istiyorsunuz?"

#: ../apport/ui.py:837
msgid "Unknown symptom"
msgstr "Bilinmeyen belirti"

#: ../apport/ui.py:838
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "\"%s\" belirtisi bilinmiyor."

#: ../apport/ui.py:874
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""

#: ../apport/ui.py:890
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Bu iletiyi kapattıktan sonra lütfen bununla ilgili sorunu bildirmek için bir "
"uygulama penceresine tıklayın."

#: ../apport/ui.py:907 ../apport/ui.py:916
msgid "xprop failed to determine process ID of the window"
msgstr "xprop, pencrenin işlem kimliğini saptamada başarısız oldu"

#: ../apport/ui.py:931
#, fuzzy, python-format
msgid "%(prog)s <report number>"
msgstr "%prog <rapor numarası>"

#: ../apport/ui.py:932
msgid "Specify package name."
msgstr "Paket adı belirtin."

#: ../apport/ui.py:938 ../apport/ui.py:1070
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Rapora fazladan bir etiket ekleyin. Birçok kez belirtilmiş olabilir."

#: ../apport/ui.py:976
#, fuzzy, python-format
msgid ""
"%(prog)s [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../apport/ui.py:987
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Hata dosyalama kipinde başlat. --package ve isteğe bağlı --pid, veya sadece "
"--pid gerektirir. Eğer hiçbiri belirtilmezse, bilinen belirtilerin listesini "
"göster. (Kastedilen; eğer tek bir argüman verilirse.)"

#: ../apport/ui.py:996
msgid "Click a window as a target for filing a problem report."
msgstr "Bir sorunu bildirmek için hedef olarak bir pencereye tıklayın."

#: ../apport/ui.py:1005
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "Hata güncelleme kipinde başlat. Seçime bağlı --package alınabilir."

#: ../apport/ui.py:1014
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Bir belirti için hata raporu dosyala. (Kastedilen; eğer belirti adı sadece "
"argüman olarak verilirse.)"

#: ../apport/ui.py:1023
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"--dosya-hata modunda paket adını belirtin. Bir -pid belirtilmişse, bu "
"seçenek opsiyoneldir. (Paket adı tek argüman olarak verilmişse uygulanır.)"

#: ../apport/ui.py:1034
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"--file-bug kipinde çalışacak bir program belirtebilirsiniz. Eğer "
"belirtilmişse, hata raporu daha fazla ayrıntı içerecektir.(PID 'in tek "
"parametre olarak verilmesi durumu kastedilmiştir)"

#: ../apport/ui.py:1042
msgid "The provided pid is a hanging application."
msgstr "Belirtilen pid (program id) askıdaki bir uygulama"

#: ../apport/ui.py:1050
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Hata raporunu %s'te beklemekte olanlar yerine .apport veya .crash "
"dosyalarından bildirin. (Eğer dosya adı verilen tek argüman ise)"

#: ../apport/ui.py:1060
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"Hata belirtme kipinde, toplanan bilgileri raporlamak yerine onları bir "
"dosyaya kaydedin. Bu dosya daha sonra farklı bir makineden raporlanabilir."

#: ../apport/ui.py:1078
msgid "Print the Apport version number."
msgstr "Apport sürüm numarasını yazdır."

#: ../apport/ui.py:1240
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Bu, çökmeyi incelemek için bir uçbirim penceresinde \"apport-retrace\" "
"komutunu çalıştıracak."

#: ../apport/ui.py:1244
msgid "Run gdb session"
msgstr "gdb oturumunu çalıştır"

#: ../apport/ui.py:1245
msgid "Run gdb session without downloading debug symbols"
msgstr "gdb oturumunu böcek temizleme simgelerini indirmeden çalıştır"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1247
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "%s dosyasını tümüyle sembolik küme iziyle güncelle"

#: ../apport/ui.py:1309
msgid "Can't remember send report status settings"
msgstr "Rapor gönderme durum ayarları hatırlanamıyor"

#: ../apport/ui.py:1313
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""
"Çökme rapor durumu kaydetme başarısız. Otomatik veya asla bildirme kipi "
"ayarlanamıyor."

#: ../apport/ui.py:1396 ../apport/ui.py:1409
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Bu problem raporu, artık yüklü olmayan bir programa ait."

#: ../apport/ui.py:1433
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Çökme olduktan sonra değişime uğrayan %s yazılımıyla ilgili sorun oluştu."

#: ../apport/ui.py:1494 ../apport/ui.py:1618 ../apport/ui.py:1869
msgid "This problem report is damaged and cannot be processed."
msgstr "Bu sorun raporu hasarlı, bu nedenle işlenemiyor."

#: ../apport/ui.py:1503
msgid "This report is about a package that is not installed."
msgstr ""

#: ../apport/ui.py:1511
msgid "An error occurred while attempting to process this problem report:"
msgstr "Bu sorun raporunu işlemeye çalışırken bir hata oluştu:"

#: ../apport/ui.py:1528
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""

#: ../apport/ui.py:1533
#, python-format
msgid "%s snap"
msgstr ""

#: ../apport/ui.py:1534
#, python-format
msgid "%s deb package"
msgstr ""

#: ../apport/ui.py:1575
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../apport/ui.py:1580
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../apport/ui.py:1679
msgid "Could not determine the package or source package name."
msgstr "Paket ya da kaynak kod paketi adı belirlenemedi."

#: ../apport/ui.py:1704
msgid "Unable to start web browser"
msgstr "Ağ tarayıcı başlatılamıyor"

#: ../apport/ui.py:1705
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "%s açmak için ağ tarayıcı başlatılamıyor."

#: ../apport/ui.py:1815
msgid "Network problem"
msgstr "Ağ sorunu"

#: ../apport/ui.py:1819
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Çöküş veritabanına bağlanılamıyor, lütfen internet bağlantınızı kontrol edin."

#: ../apport/ui.py:1851
msgid "Memory exhaustion"
msgstr "Yetersiz bellek"

#: ../apport/ui.py:1853
msgid "Your system does not have enough memory to process this crash report."
msgstr "Sisteminiz bu çökme raporunu işlemek için yeterli belleğe sahip değil."

#: ../apport/ui.py:1904
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Sorun raporlanamadı:\n"
"\n"
"%s"

#: ../apport/ui.py:1960 ../apport/ui.py:1972
msgid "Problem already known"
msgstr "Sorun önceden bildirilmiş"

#: ../apport/ui.py:1962
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Bu sorun web tarayıcısında görüntülenmekte olan hata raporuyla önceden "
"bildirilmiş. Lütfen geliştiricilere yardımcı olabilecek ek bir bilgi ekleyip "
"ekleyemeyeceğinize bakın."

#: ../apport/ui.py:1974
msgid "This problem was already reported to developers. Thank you!"
msgstr "Bu sorun daha önce geliştiricilere bildirildi. Teşekkür ederiz!"

#: ../bin/apport-cli.py:84
msgid "Press any key to continue..."
msgstr "Devam etmek için bir tuşa basın..."

#: ../bin/apport-cli.py:91
msgid "What would you like to do? Your options are:"
msgstr "Ne yapmak istersiniz? Seçenekleriniz:"

#: ../bin/apport-cli.py:104
#, python-format
msgid "Please choose (%s):"
msgstr "Lütfen seçin (%s):"

#: ../bin/apport-cli.py:172
#, python-format
msgid "(%i bytes)"
msgstr "(%i sekiz ikil)"

#: ../bin/apport-cli.py:174 ../gtk/apport-gtk.py:169 ../kde/apport-kde.py:406
msgid "(binary data)"
msgstr "(ikili veri)"

#: ../bin/apport-cli.py:209 ../gtk/apport-gtk.py:208 ../gtk/apport-gtk.ui.h:6
#: ../kde/apport-kde.py:199
msgid "Send problem report to the developers?"
msgstr "Hata raporu geliştiricilere gönderilsin mi?"

#: ../bin/apport-cli.py:211
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Problem raporu gönderildikten sonra, lütfen web tarayıcınızda otomatik\n"
"olarak açılan  sayfada yer alan formu doldurun."

#: ../bin/apport-cli.py:218
#, python-format
msgid "&Send report (%s)"
msgstr "Rapor &Gönder (%s)"

#: ../bin/apport-cli.py:223
msgid "&Examine locally"
msgstr "Yerel olarak &İncele"

#: ../bin/apport-cli.py:227
msgid "&View report"
msgstr "Rapor Görüntü&le"

#: ../bin/apport-cli.py:230
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Rapor dosyasını, daha sonra gönderme veya başka bir yere kopyalanması için "
"saklayın."

#: ../bin/apport-cli.py:235
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Programın bu sürümünün gelecekteki çökmelerini iptal et ve &yoksay"

#: ../bin/apport-cli.py:238 ../bin/apport-cli.py:332 ../bin/apport-cli.py:366
#: ../bin/apport-cli.py:389
msgid "&Cancel"
msgstr "&Vazgeç"

#: ../bin/apport-cli.py:273
msgid "Problem report file:"
msgstr "Sorun rapor dosyası:"

#: ../bin/apport-cli.py:279 ../bin/apport-cli.py:284
msgid "&Confirm"
msgstr "&Onayla"

#: ../bin/apport-cli.py:283
#, python-format
msgid "Error: %s"
msgstr "Hata: %s"

#: ../bin/apport-cli.py:289 ../kde/apport-kde.py:462
msgid "Collecting problem information"
msgstr "Sorun bilgileri toplanıyor"

#: ../bin/apport-cli.py:291
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Toplanan bilgiler geliştiriciler için uygulama geliştirmek için "
"gönderilebilir. \n"
"Bu birkaç dakika sürebilir."

#: ../bin/apport-cli.py:307 ../gtk/apport-gtk.ui.h:17 ../kde/apport-kde.py:511
msgid "Uploading problem information"
msgstr "Sorun bilgileri yükleniyor"

#: ../bin/apport-cli.py:309
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Toplanan bilgiler hata takip sistemi için gönderiliyor.\n"
"Bu birkaç dakika sürebilir."

#: ../bin/apport-cli.py:365
msgid "&Done"
msgstr "&Bitti"

#: ../bin/apport-cli.py:371
msgid "none"
msgstr "hiçbiri"

#: ../bin/apport-cli.py:373
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Seçili: %s. Birden fazla seçenek:"

#: ../bin/apport-cli.py:390
msgid "Choices:"
msgstr "Seçenekler:"

#: ../bin/apport-cli.py:404
msgid "Path to file (Enter to cancel):"
msgstr "Dosya yolu (Iptal etmek için girin):"

#: ../bin/apport-cli.py:410
msgid "File does not exist."
msgstr "Dosya mevcut değil."

#: ../bin/apport-cli.py:412
msgid "This is a directory."
msgstr "Bu bir dizin."

#: ../bin/apport-cli.py:418
msgid "To continue, you must visit the following URL:"
msgstr "Devam etmek için, aşağıdaki URL'yi ziyaret etmelisiniz:"

#: ../bin/apport-cli.py:421
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Şimdi tarayıcıda açabilirsiniz, ya da bu URL'yi başka bilgisayardaki bir "
"tarayıcıya kopyalayabilirsiniz."

#: ../bin/apport-cli.py:427
msgid "Launch a browser now"
msgstr "Tarayıcıyı aç"

#: ../bin/apport-cli.py:443
msgid "No pending crash reports. Try --help for more information."
msgstr "Bekleyen çökme raporu yok. Daha fazla bilgi için --help 'i deneyin."

#: ../bin/apport-retrace.py:44
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "Raporda yeni işaretlemeler yapmak yerine bunları stdout'a yazın."

#: ../bin/apport-retrace.py:53
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Raporun son dökümü ile bir interaktif gdb oturumu başlat (-o yoksayılır; "
"raporun üzerine yazmaz)"

#: ../bin/apport-retrace.py:62
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr "Asıl raporu değiştirmek yerine düzeltilmiş raporu verilen dosyaya yaz"

#: ../bin/apport-retrace.py:72
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Kutup yığınını küme izleme düzeltmesinden sonra rapordan geri al"

#: ../bin/apport-retrace.py:80
msgid "Override report's CoreFile"
msgstr "Raporun ÇekirdekDosyası'nı Geçersiz Kıl"

#: ../bin/apport-retrace.py:86
msgid "Override report's ExecutablePath"
msgstr "Raporun çalıştırılabilir yolunu geçersiz kıl (ExecutablePath)"

#: ../bin/apport-retrace.py:92
msgid "Override report's ProcMaps"
msgstr "Raporun ProcMap'lerini Geçersiz Kıl"

#: ../bin/apport-retrace.py:98
msgid "Rebuild report's Package information"
msgstr "Raporların Yedek bilgisini onar"

#: ../bin/apport-retrace.py:105
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Geçici bir test alanı oluşturup indirdiğiniz gerekli paketleri ve böcek "
"temizleme sembollerini buraya kurun; bu seçenek olmadan gerekli paketlerin "
"ve böcek temizleme sembollerinin daha önce sisteme yüklendiğini "
"varsayacaktır. Deliller paketleme sistemi yapılandırma ana dizinini; eğer "
"\"sistem\" olarak belirlerseniz sistem yapılandırma dosyalarını işaret eder, "
"bu durumda yalnızca şu anda çalışan dağıtımda meydana gelen çökmelerin "
"kaynağına gidebilir."

#: ../bin/apport-retrace.py:119
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""

#: ../bin/apport-retrace.py:129
msgid "Report download/install progress when installing packages into sandbox"
msgstr "Paketler sandbox içine kurulurken indirme/yüklemeyi raporla"

#: ../bin/apport-retrace.py:136
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "Yığın işlemi için kayıt iletilerinin başına zaman etiketleri ekle"

#: ../bin/apport-retrace.py:142
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr "Raporlarda kaynağı tanımlanmış üçüncü parti depoları oluştur ve kullan"

#: ../bin/apport-retrace.py:150
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Sandbox içine indirilmiş paketler için önbellek dizini"

#: ../bin/apport-retrace.py:156
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Açılmamış paketlerin dizini. Sonraki çalıştırmalar, daha önceden indirilmiş "
"herhangi paketin de bu sandbox'a çıkartılacağını varsayacak."

#: ../bin/apport-retrace.py:167 ../bin/apport-valgrind.py:97
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"Fazladan bir paketi sandbox içine yükle (birden çok kez belirtilebilir)"

#: ../bin/apport-retrace.py:174
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Çökme Veritabanı Doğrulama bilgisini içeren bir dosya yolu belirtin. Bu "
"çökme ID'si belirlenirken kaynağına ulaşılmış yığın izlerinini yüklemede "
"kullanılır. (Eğer -g, -o veya -s belirtiymediyse)"

#: ../bin/apport-retrace.py:184
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Yeniden oluşturulmuş yığın izlerini göster ve bunları çökme veritabanına "
"göndermeden önce onay al."

#: ../bin/apport-retrace.py:192
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr "Kopya sqlite veritabanının yolu (varsayılan: kopya kontrolü yok)"

#: ../bin/apport-retrace.py:200
msgid "Do not add StacktraceSource to the report."
msgstr "Rapora StacktraceSource ekleme."

#: ../bin/apport-retrace.py:213
msgid "You cannot use -C without -S. Stopping."
msgstr "-S olmaksızın -C kullanamazsınız. Durduruluyor."

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:243
msgid "OK to send these as attachments? [y/n]"
msgstr "Eklenti olarak gönderilsinler mi? [y/n]"

#: ../bin/apport-unpack.py:29
#, fuzzy, python-format
msgid "%(prog)s <report> <target directory>"
msgstr "Kullanım: %s <rapor> <hedef dizin>"

#: ../bin/apport-unpack.py:31
msgid "Report file to unpack"
msgstr ""

#: ../bin/apport-unpack.py:33
msgid "directory to unpack report to"
msgstr ""

#: ../bin/apport-unpack.py:59
msgid "Destination directory exists and is not empty."
msgstr "Hedef dizin zaten mevcut ve boş değil."

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Ayrıntılar için man sayfasına bakın."

#: ../bin/apport-valgrind.py:46
msgid "specify the log file name produced by valgrind"
msgstr "valgrind tarafından oluşturulan günlük dosya adını belirtin"

#: ../bin/apport-valgrind.py:52
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"önceden oluşturulmuş sanbox dizinini (SDIR) tekrar kullan veya bulunmuyorsa "
"oluştur"

#: ../bin/apport-valgrind.py:60
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"ek hata ayıklayıcı sembolleri için sandbox dizinini tekrar kullanma veya "
"oluşturma ancak, sadece yüklü hata ayıklama sembollerini kullan."

#: ../bin/apport-valgrind.py:69
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"önceden oluşturulmuş önbellek dizinini (CDIR) tekrar kullan veya "
"bulunmuyorsa oluştur"

#: ../bin/apport-valgrind.py:78
msgid "report download/install progress when installing packages into sandbox"
msgstr "paketleri sandbox içine kurarken indirme/yükleme sürecini bildir"

#: ../bin/apport-valgrind.py:86
msgid ""
"the executable that is run under valgrind's memcheck tool for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:129
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Hata: %s yürütülebilir değil. Durduruluyor."

#: ../data/apportcheckresume.py:68
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""

#: ../data/apportcheckresume.py:73
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""

#: ../data/apportcheckresume.py:81
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Kalan işlem bitmesine çok yakın bir yerde takıldı ve normal bir biçimde "
"tamamlanmış gibi görünecek."

#: ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Sisteminiz şimdi kararsız hale gelebilir ve yeniden başlatılması gerekebilir."

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr "Bir sorunu bildir..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Geliştiricilere bir arıza bildir"

#: ../gtk/apport-gtk.py:185
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Üzgünüz, %s uygulaması beklenmedik şekilde durdu."

#: ../gtk/apport-gtk.py:188
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Üzgünüz, %s beklenmedik bir şekilde kapandı."

#: ../gtk/apport-gtk.py:193 ../kde/apport-kde.py:214 ../kde/apport-kde.py:266
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Üzgünüz, %s içsel bir hatayla karşılaştı."

#: ../gtk/apport-gtk.py:216 ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:207
msgid "Send"
msgstr "Gönder"

#: ../gtk/apport-gtk.py:234 ../gtk/apport-gtk.py:666 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:330
msgid "Show Details"
msgstr "Ayrıntıları Göster"

#: ../gtk/apport-gtk.py:247 ../kde/apport-kde.py:258 ../kde/apport-kde.py:276
msgid "Continue"
msgstr "Devam Et"

#: ../gtk/apport-gtk.py:271
#, python-format
msgid "The application %s has stopped responding."
msgstr "%s uygulaması yanıt vermeyi durdurdu."

#: ../gtk/apport-gtk.py:275
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "\"%s\" programı yanıt vermeyi durdurdu."

#: ../gtk/apport-gtk.py:292 ../kde/apport-kde.py:222
#, python-format
msgid "Package: %s"
msgstr "Paket: %s"

#: ../gtk/apport-gtk.py:298 ../kde/apport-kde.py:229
msgid "Sorry, a problem occurred while installing software."
msgstr "Üzgünüz, yazılım yüklenirken bir hatayla karşılaşıldı."

#: ../gtk/apport-gtk.py:310 ../gtk/apport-gtk.py:334 ../kde/apport-kde.py:238
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "%s uygulaması bir iç hata ile karşılaştı."

#: ../gtk/apport-gtk.py:316 ../kde/apport-kde.py:245
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "%s yazılımı beklenmedik bir şekilde kapandı."

#: ../gtk/apport-gtk.py:347 ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:271
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"Daha fazla sorunla karşılaşırsanız bilgisayarınız yeniden başlatmayı deneyin."

#: ../gtk/apport-gtk.py:352 ../kde/apport-kde.py:278
msgid "Ignore future problems of this type"
msgstr "İlerde oluşabilecek bu türden sorunları yok say"

#: ../gtk/apport-gtk.py:670 ../kde/apport-kde.py:327
msgid "Hide Details"
msgstr "Ayrıntıları Gizle"

#: ../gtk/apport-gtk.ui.h:1 ../kde/apport-kde.py:552 ../kde/apport-kde.py:595
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Vazgeç"

#: ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "Tamam"

#: ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Çökme raporu"

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b> Üzgünüz, içsel bir hata oluştu.</b></big>"

#: ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "Bunu ileride hatırla"

#: ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Bu yazılım sürümünün gelecekteki sorunlarını görmezden gel"

#: ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "Bu uygulamayı yeniden çalıştır"

#: ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "Yerel olarak _İncele"

#: ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "Gönderme"

#: ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Sorunla ilgili bilgi toplanıyor</b></big>"

#: ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Bilgi, bildirdiğiniz sorunun çözümünde geliştiricilere yardımı "
"dokunabileceği için toplanıyor."

#: ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Sorun bilgileri yükleniyor</b></big>"

#: ../gtk/apport-gtk.ui.h:19 ../kde/apport-kde.py:513
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Toplanan bilgi hata izleme sistemine gönderiliyor. Bu, birkaç dakika "
"sürebilir."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport çökme dosyası"

#: ../kde/apport-kde.py:261
msgid "Leave Closed"
msgstr "Kapalı Bırak"

#: ../kde/apport-kde.py:262 ../kde/apport-kde.py:432
msgid "Relaunch"
msgstr "Yeniden başlat"

#: ../kde/apport-kde.py:355
msgid "Username:"
msgstr "Kullanıcı Adı:"

#: ../kde/apport-kde.py:356
msgid "Password:"
msgstr "Parola:"

#: ../kde/apport-kde.py:461
msgid "Collecting Problem Information"
msgstr "Sorun Bilgileri Toplanıyor"

#: ../kde/apport-kde.py:464
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Toplanan bilgi, uygulamanın geliştirilmesi için geliştiricilere "
"gönderilebilir. Bu, birkaç dakika sürebilir."

#: ../kde/apport-kde.py:510
msgid "Uploading Problem Information"
msgstr "Sorun Bilgileri Gönderiliyor"
