# Ukrainian translation for apport
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-12-07 16:23+0100\n"
"PO-Revision-Date: 2022-10-08 17:08+0000\n"
"Last-Translator: Volodymyr Shypovych <Unknown>\n"
"Language-Team: Ukrainian <uk@li.org>\n"
"Language: uk\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2022-12-07 14:36+0000\n"
"X-Generator: Launchpad (build 41e7553f8097ce3a683f90e835708cbe7bf0006c)\n"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Зібрати системну інформацію"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Потрібно надати права, щоб зібрати потрібні дані для звітування про дану "
"проблему"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Звіти про системні помилки"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr ""
"Будь ласка введіть свій пароль для отримання длступу до звіті системних "
"програм"

#: ../apport/ui.py:165
msgid "This package does not seem to be installed correctly"
msgstr "Здається, що цей пакунок встановлено невірно"

#: ../apport/ui.py:175
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""
"Здається, це не офіційний пакунок %s. Повторіть спробу після оновлення "
"індексів доступних пакунків, якщо це не допоможе, вилучіть пов’язані "
"сторонні пакунки та повторіть спробу."

#: ../apport/ui.py:205
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"У системі встановлено застарілі версії деяких пакунків. Оновіть наступні "
"пакунки та перевірте, чи залишилася проблема:\n"
"\n"
"%s"

#: ../apport/ui.py:359
msgid "unknown program"
msgstr "невідома програма"

#: ../apport/ui.py:362
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "На жаль, програма \"%s\" несподівано закрилася"

#: ../apport/ui.py:365 ../apport/ui.py:1899
#, python-format
msgid "Problem in %s"
msgstr "Помилка у %s"

#: ../apport/ui.py:370
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"На вашому комп'ютері недостатньо вільної пам'яті для автоматичного аналізу "
"проблеми та надсилання розробникам звіту."

#: ../apport/ui.py:430 ../apport/ui.py:448 ../apport/ui.py:621
#: ../apport/ui.py:630 ../apport/ui.py:867 ../apport/ui.py:1677
#: ../apport/ui.py:1860 ../apport/ui.py:1865
msgid "Invalid problem report"
msgstr "Неправильний звіт про помилку"

#: ../apport/ui.py:431
msgid "You are not allowed to access this problem report."
msgstr "Ви не маєте доступу до цього звіту."

#: ../apport/ui.py:439
msgid "Error"
msgstr "Помилка"

#: ../apport/ui.py:441
msgid "There is not enough disk space available to process this report."
msgstr "Недостатньо місця на диску для обробки цього звіту."

#: ../apport/ui.py:479
msgid "No PID specified"
msgstr "PID не вказано"

#: ../apport/ui.py:481
msgid "You need to specify a PID. See --help for more information."
msgstr ""
"Вам потрібно зазначити PID. Перегляньте --help для більш детальної інформації"

#: ../apport/ui.py:492 ../apport/ui.py:597
msgid "Invalid PID"
msgstr "Неправильний PID"

#: ../apport/ui.py:493
msgid "The specified process ID does not exist."
msgstr "Зазначеного ідентифікатора процесу не існує."

#: ../apport/ui.py:498
msgid "Not your PID"
msgstr "Не ваш PID"

#: ../apport/ui.py:499
msgid "The specified process ID does not belong to you."
msgstr "Вказаний ідентифікатор процесу вам не належить."

#: ../apport/ui.py:554
msgid "No package specified"
msgstr "Не вказано пакунок"

#: ../apport/ui.py:556
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Необхідно вказати пакунок або PID. Наберіть --help для отримання додаткової "
"інформації."

#: ../apport/ui.py:584
msgid "Permission denied"
msgstr "У доступі відмовлено"

#: ../apport/ui.py:586
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Зазначений процес Вам не належить. Будь ласка, запустіть програму як власник "
"процесу або як root."

#: ../apport/ui.py:599
msgid "The specified process ID does not belong to a program."
msgstr "Зазначений процес ID не належить до програми."

#: ../apport/ui.py:623
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Симптоматичний скрипт %s не може визначити постраждалих пакунків"

#: ../apport/ui.py:631
#, python-format
msgid "Package %s does not exist"
msgstr "Пакунку %s не існує"

#: ../apport/ui.py:660 ../apport/ui.py:872 ../apport/ui.py:905
#: ../apport/ui.py:915
msgid "Cannot create report"
msgstr "Неможливо створити звіт"

#: ../apport/ui.py:675 ../apport/ui.py:734 ../apport/ui.py:752
msgid "Updating problem report"
msgstr "Оновлення звіту про проблему"

#: ../apport/ui.py:677
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Ви не є автором або підписником цього звіту про проблему, або звіт вже "
"існує, або вже закритий.\n"
"Будь-ласка, створіть новий звіт за допомогою \"apport-bug\"."

#: ../apport/ui.py:689
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Ви не створювали даний звіт. Набагато легше маркувати помилку як ту що вже "
"існує, ніж створювати свої коментарі та відправляти нову помилку.\n"
"\n"
"Надалі, ми рекомендуємо Вам подати нове повідомлення про помилку з "
"використанням \"apport-bug\", та коментувати помилку у тому ж файлі.\n"
"\n"
"Ви справді бажаєте продовжити?"

#: ../apport/ui.py:735 ../apport/ui.py:753
msgid "No additional information collected."
msgstr "Не зібрано додаткової інформації."

#: ../apport/ui.py:816
msgid "What kind of problem do you want to report?"
msgstr "Про яку проблему ви бажаєте повідомити?"

#: ../apport/ui.py:837
msgid "Unknown symptom"
msgstr "Невідомий симптом"

#: ../apport/ui.py:838
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Симптом «%s» не відомий"

#: ../apport/ui.py:874
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""
"Даний параметр вікна не можна використовувати на Wayland\n"
"\n"
"Будь ласка, знайдіть ID процесу у вікні та запустіть 'ubuntu-bug <ID "
"процесу>'\n"
"\n"
"ID процесу можна знайти, запустивши програму \"Системний монітор\". На "
"вкладці \"Процеси\" шукаєте потрібну Вам програму. ID процесу – це номер, "
"вказаний у колонці ID."

#: ../apport/ui.py:890
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Після того, як сховаєте дане повідомлення, будь-ласка, клацніть на вікно "
"програми для того, щоб відіслати звіт про помилку."

#: ../apport/ui.py:907 ../apport/ui.py:916
msgid "xprop failed to determine process ID of the window"
msgstr "Помилка xprop: не вдалося визначити ID процесу вікна"

#: ../apport/ui.py:931
#, python-format
msgid "%(prog)s <report number>"
msgstr ""

#: ../apport/ui.py:932
msgid "Specify package name."
msgstr "Вкажіть назву пакунку."

#: ../apport/ui.py:938 ../apport/ui.py:1070
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Додати додаткову мітку до звіту. Може бути задано декілька разів."

#: ../apport/ui.py:976
#, python-format
msgid ""
"%(prog)s [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:987
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Запуск у режимі запису помилки у файл. Вимагає --package і факультативно --"
"pid, або просто --pid. Якщо ні одного не вказано, показати список відомих "
"симптомів. (Мається на увазі якщо задано один аргумент.)"

#: ../apport/ui.py:996
msgid "Click a window as a target for filing a problem report."
msgstr "Натисніть на цільове вікно для заповнення звіту про помилку."

#: ../apport/ui.py:1005
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Запустити у режимі оновлення помилки. Може виконуватися з ключем --package."

#: ../apport/ui.py:1014
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Відправити звіт про помилку з симптомом. (Мається на увазі, якщо ім'я "
"симптому дано як єдиний аргумент.)"

#: ../apport/ui.py:1023
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Вкажіть назву пакунку у режимі --file-bug. Необов’язково якщо вказано --pid. "
"(Припустимо що назва пакунку вказана у якості єдиного аргументу)"

#: ../apport/ui.py:1034
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Вкажіть програму, що виконується, у режимі --file-bug. У цьому випадку звіт "
"про помилку міститиме більше інформації. (Мається на увазі, що вказано "
"єдиний аргумент- pid.)"

#: ../apport/ui.py:1042
msgid "The provided pid is a hanging application."
msgstr "Вказаний ідентифікатор належить процесу, який не відповідає."

#: ../apport/ui.py:1050
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Повідомити про аварійне завершення із наданого файлу .apport або .crash "
"замість файлів у черзі в %s. (За умови, що файл надано у якості єдиного "
"параметру.)"

#: ../apport/ui.py:1060
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"У режимі збору помилок замість надсилати зібрану інформацію, збережіть її у "
"файл. Цей файл можна буде відправити пізніше з іншого комп'ютера."

#: ../apport/ui.py:1078
msgid "Print the Apport version number."
msgstr "Надрукувати номер версії Apport ."

#: ../apport/ui.py:1240
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Буде здійснено запуск «apport-retrace» у вікні терміналу для перевірки "
"аварійного завершення роботи."

#: ../apport/ui.py:1244
msgid "Run gdb session"
msgstr "Запустити сеанс gdb"

#: ../apport/ui.py:1245
msgid "Run gdb session without downloading debug symbols"
msgstr "Запустити сеанс gdb, оминувши завантаження символів відлагодження"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1247
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Оновити %s з повним відстеженням символьного стеку"

#: ../apport/ui.py:1309
msgid "Can't remember send report status settings"
msgstr "Неможливо запам'ятати параметри стану для надсилання звіту"

#: ../apport/ui.py:1313
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../apport/ui.py:1396 ../apport/ui.py:1409
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Цей звіт про помилку належить до програми, якої більше немає у системі."

#: ../apport/ui.py:1433
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../apport/ui.py:1494 ../apport/ui.py:1618 ../apport/ui.py:1869
msgid "This problem report is damaged and cannot be processed."
msgstr "Цей звіт про помилку пошкоджено та не може бути оброблено."

#: ../apport/ui.py:1503
msgid "This report is about a package that is not installed."
msgstr ""

#: ../apport/ui.py:1511
msgid "An error occurred while attempting to process this problem report:"
msgstr "Сталася помилка при спробі обробки звіту:"

#: ../apport/ui.py:1528
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""
"У вас встановлено дві версії цього застосунку. Про помилку в якій з них ви "
"волієте повідомити?"

#: ../apport/ui.py:1533
#, python-format
msgid "%s snap"
msgstr ""

#: ../apport/ui.py:1534
#, python-format
msgid "%s deb package"
msgstr "%s пакунок deb"

#: ../apport/ui.py:1575
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../apport/ui.py:1580
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../apport/ui.py:1679
msgid "Could not determine the package or source package name."
msgstr "Не вдалося визначити ім'я пакунку або ім'я пакунку з вихідним кодом."

#: ../apport/ui.py:1704
msgid "Unable to start web browser"
msgstr "Неможливо запустити оглядач тенет"

#: ../apport/ui.py:1705
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Неможливо запустити оглядач тенет, щоб відкрити %s."

#: ../apport/ui.py:1815
msgid "Network problem"
msgstr "Проблема з мережею"

#: ../apport/ui.py:1819
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Не вдається під'єднатися до пошкодженої бази даних, будь ласка, перевірте "
"з'єднання з мережею Інтернет."

#: ../apport/ui.py:1851
msgid "Memory exhaustion"
msgstr "Пам'ять вичерпано"

#: ../apport/ui.py:1853
msgid "Your system does not have enough memory to process this crash report."
msgstr "У системі недостатньо пам'яті для обробки цього звіту про помилку."

#: ../apport/ui.py:1904
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Не вдається повідомити про помилку:\n"
"\n"
"%s"

#: ../apport/ui.py:1960 ../apport/ui.py:1972
msgid "Problem already known"
msgstr "Про помилку вже відомо"

#: ../apport/ui.py:1962
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Про цю помилку вже відомо. Звіт про неї відкритий у вашому браузері. Будь "
"ласка, перевірте, чи можете ви додати до нього іншу корисну інформацію, яка "
"могла б допомогти розробникам."

#: ../apport/ui.py:1974
msgid "This problem was already reported to developers. Thank you!"
msgstr "Про цю проблему розробникам вже відомо. Дякуємо!"

#: ../bin/apport-cli.py:84
msgid "Press any key to continue..."
msgstr "Натисніть будь-яку клавішу для продовження..."

#: ../bin/apport-cli.py:91
msgid "What would you like to do? Your options are:"
msgstr "Що ви бажаєте зробити? Варіянти вибору:"

#: ../bin/apport-cli.py:104
#, python-format
msgid "Please choose (%s):"
msgstr "Будь ласка, виберіть (%s):"

#: ../bin/apport-cli.py:172
#, python-format
msgid "(%i bytes)"
msgstr "(%i байт)"

#: ../bin/apport-cli.py:174 ../gtk/apport-gtk.py:169 ../kde/apport-kde.py:406
msgid "(binary data)"
msgstr "(двійкові дані)"

#: ../bin/apport-cli.py:209 ../gtk/apport-gtk.py:208 ../gtk/apport-gtk.ui.h:6
#: ../kde/apport-kde.py:199
msgid "Send problem report to the developers?"
msgstr "Надіслати розробникам звіт про помилку?"

#: ../bin/apport-cli.py:211
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Після того, як звіт буде відправлено, заповніть форму\n"
"у вікні браузера, яке автоматично відкрилося."

#: ../bin/apport-cli.py:218
#, python-format
msgid "&Send report (%s)"
msgstr "&Надіслати звіт (%s)"

#: ../bin/apport-cli.py:223
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:227
msgid "&View report"
msgstr "&Переглянути звіт"

#: ../bin/apport-cli.py:230
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Зберегти файл звіту для подальшого відправлення або копіювання будь-куди"

#: ../bin/apport-cli.py:235
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Скасувати та &ігнорувати майбутні збої у цій версії програми"

#: ../bin/apport-cli.py:238 ../bin/apport-cli.py:332 ../bin/apport-cli.py:366
#: ../bin/apport-cli.py:389
msgid "&Cancel"
msgstr "&Скасувати"

#: ../bin/apport-cli.py:273
msgid "Problem report file:"
msgstr "Файл звіту про помилку:"

#: ../bin/apport-cli.py:279 ../bin/apport-cli.py:284
msgid "&Confirm"
msgstr "&Підтвердити"

#: ../bin/apport-cli.py:283
#, python-format
msgid "Error: %s"
msgstr "Помилка: %s"

#: ../bin/apport-cli.py:289 ../kde/apport-kde.py:462
msgid "Collecting problem information"
msgstr "Збір інформації про помилку"

#: ../bin/apport-cli.py:291
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Зібрану інформацію може бути направлено розробникам\n"
"для покращення програми. Це може зайняти декілька хвилин."

#: ../bin/apport-cli.py:307 ../gtk/apport-gtk.ui.h:17 ../kde/apport-kde.py:511
msgid "Uploading problem information"
msgstr "Вивантаження даних щодо проблеми"

#: ../bin/apport-cli.py:309
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Зібрана інформація надсилається до системи відстежування помилок.\n"
"Це може зайняти декілька хвилин."

#: ../bin/apport-cli.py:365
msgid "&Done"
msgstr "&Завершено"

#: ../bin/apport-cli.py:371
msgid "none"
msgstr "немає"

#: ../bin/apport-cli.py:373
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Вибрано: %s. Декілька варіянтів:"

#: ../bin/apport-cli.py:390
msgid "Choices:"
msgstr "Вибір:"

#: ../bin/apport-cli.py:404
msgid "Path to file (Enter to cancel):"
msgstr "Шлях до файлу (Enter для скасування):"

#: ../bin/apport-cli.py:410
msgid "File does not exist."
msgstr "Файлу не існує"

#: ../bin/apport-cli.py:412
msgid "This is a directory."
msgstr "Це каталог."

#: ../bin/apport-cli.py:418
msgid "To continue, you must visit the following URL:"
msgstr "Щоб продовжити, ви повинні пройти за адресою:"

#: ../bin/apport-cli.py:421
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Ви можете запустити браузер зараз або скопіювати цю адресу у браузер на "
"іншому комп'ютері."

#: ../bin/apport-cli.py:427
msgid "Launch a browser now"
msgstr "Запустити браузер"

#: ../bin/apport-cli.py:443
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Немає звітів про помилки у очікуванні. Спробуйте --help для детальної "
"інформації."

#: ../bin/apport-retrace.py:44
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "Не вкладайте нові записи у звіт, а долучайте їх до stdout."

#: ../bin/apport-retrace.py:53
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Початок інтерактивної GDB сесії з  дампом у звіті (-o ігнорувати, не "
"записувати у звіт)"

#: ../bin/apport-retrace.py:62
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Записати змінений звіт до вказаного файлу замість заміни оригінального звіту"

#: ../bin/apport-retrace.py:72
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Зняти дамп зі звіту після трасування стеку регенерації"

#: ../bin/apport-retrace.py:80
msgid "Override report's CoreFile"
msgstr "Перекрити звіти CoreFile"

#: ../bin/apport-retrace.py:86
msgid "Override report's ExecutablePath"
msgstr "Перекрити звіти ExecutablePath"

#: ../bin/apport-retrace.py:92
msgid "Override report's ProcMaps"
msgstr "Перекрити звіти ProcMaps"

#: ../bin/apport-retrace.py:98
msgid "Rebuild report's Package information"
msgstr "Перебудувати звітовий пакунок інформації"

#: ../bin/apport-retrace.py:105
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Створити тимчасове середовище, далі - завантажити/встановити у ньому "
"необхідні пакунки й налагоджувальні символи; без цього параметру очікується, "
"що необхідні пакунки та налагоджувальні символи у системі вже встановлено. "
"Аргумент вказує на базову теку конфігурації системи пакунків; якщо Ви "
"вказали \"system\", буде використано системні файли конфігурації, але лише у "
"разі виявлення аварійних ситуацій, що виникли у випуску системи, яка працює "
"на дану мить."

#: ../bin/apport-retrace.py:119
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""

#: ../bin/apport-retrace.py:129
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""
"Сповіщати про хід виконання завантаження/встановлення пакунків у тимчасовому "
"середовищі"

#: ../bin/apport-retrace.py:136
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:142
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Створення і використання сторонніх сховищ на основі початкових, вказаних у "
"звітах"

#: ../bin/apport-retrace.py:150
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""
"Тека для збереження пакунків, що заванатажуються у тимчасове середовище"

#: ../bin/apport-retrace.py:156
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Директорія для розпакування пакунків. При наступних запусках усі вже "
"завантажені пакунки будуть розпаковуватися у це ізольоване оточення."

#: ../bin/apport-retrace.py:167 ../bin/apport-valgrind.py:97
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"Встановити у тимчасове середовище додатковий пакунок (може встановлюватися "
"декілька разів)"

#: ../bin/apport-retrace.py:174
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Шлях до файлу з інформацією про автентифікацію бази даних про крахи. "
"Використовується лише якщо вказано ID краху для відсилання трасувань стеку "
"(за умови, що ні -g, -o , ані -s не вказано)"

#: ../bin/apport-retrace.py:184
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Показати перетрасований стек та запитати підтвердження перед відправленням "
"його у базу аварій."

#: ../bin/apport-retrace.py:192
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Шлях до дублікату бази даних sqlite (типово: немає дублікату для перевірки)"

#: ../bin/apport-retrace.py:200
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../bin/apport-retrace.py:213
msgid "You cannot use -C without -S. Stopping."
msgstr "Неможна використовувати -C без -S. Зупинка."

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:243
msgid "OK to send these as attachments? [y/n]"
msgstr "Відіслати їх як вкладення? [так/ні]"

#: ../bin/apport-unpack.py:29
#, python-format
msgid "%(prog)s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:31
msgid "Report file to unpack"
msgstr ""

#: ../bin/apport-unpack.py:33
msgid "directory to unpack report to"
msgstr ""

#: ../bin/apport-unpack.py:59
msgid "Destination directory exists and is not empty."
msgstr "Каталог адресату існує і не є порожнім."

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Дивіться подробиці у man-сторінці."

#: ../bin/apport-valgrind.py:46
msgid "specify the log file name produced by valgrind"
msgstr "вкажіть ім’я log-файлу для valgrind"

#: ../bin/apport-valgrind.py:52
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"використовувати раніше створений каталог пісочниці (SDIR) або створити його "
"якщо його не існує"

#: ../bin/apport-valgrind.py:60
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"не створювати та не використовувати каталог пісочниці для додаткових "
"символів налагодження, а покладатися лише на встановлені символи "
"налагодження."

#: ../bin/apport-valgrind.py:69
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"використовувати раніше створений каталог кешу (CDIR) або створити його якщо "
"його не існує"

#: ../bin/apport-valgrind.py:78
msgid "report download/install progress when installing packages into sandbox"
msgstr ""
"показувати поступ завантаження/встановлення під час встановлення пакунків у "
"пісочницю"

#: ../bin/apport-valgrind.py:86
msgid ""
"the executable that is run under valgrind's memcheck tool for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:129
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Помилка: %s — не виконуваний файл. Зупинка."

#: ../data/apportcheckresume.py:68
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Це сталося під час попереднього сеансу призупинення роботи і призвело до "
"неможливості належного відновлення роботи системи."

#: ../data/apportcheckresume.py:73
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Це сталося під час попереднього сеансу присипляння і призвело до "
"неможливості належного відновлення роботи системи."

#: ../data/apportcheckresume.py:81
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Обробка даних звіту зависла дуже близько до кінця і буде, як видається, "
"завершено нормально."

#: ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Система може стати нестабільною, можливо буде потрібне перезавантаження."

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr "Повідомити про помилку..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Звітувати про збій розробникам"

#: ../gtk/apport-gtk.py:185
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Вибачте, застосунок %s неочікувано зупинився."

#: ../gtk/apport-gtk.py:188
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:193 ../kde/apport-kde.py:214 ../kde/apport-kde.py:266
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Вибачте, у %s сталася внутрішня помилка."

#: ../gtk/apport-gtk.py:216 ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:207
msgid "Send"
msgstr ""

#: ../gtk/apport-gtk.py:234 ../gtk/apport-gtk.py:666 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:330
msgid "Show Details"
msgstr ""

#: ../gtk/apport-gtk.py:247 ../kde/apport-kde.py:258 ../kde/apport-kde.py:276
msgid "Continue"
msgstr ""

#: ../gtk/apport-gtk.py:271
#, python-format
msgid "The application %s has stopped responding."
msgstr "Застосунок %s перестав відповідати."

#: ../gtk/apport-gtk.py:275
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Програма \"%s\" перестала відповідати."

#: ../gtk/apport-gtk.py:292 ../kde/apport-kde.py:222
#, python-format
msgid "Package: %s"
msgstr "Пакунок: %s"

#: ../gtk/apport-gtk.py:298 ../kde/apport-kde.py:229
msgid "Sorry, a problem occurred while installing software."
msgstr "Вибачте, під час встановлення сталася помилка."

#: ../gtk/apport-gtk.py:310 ../gtk/apport-gtk.py:334 ../kde/apport-kde.py:238
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "У додатку %s сталася внутрішня помилка."

#: ../gtk/apport-gtk.py:316 ../kde/apport-kde.py:245
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:347 ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:271
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../gtk/apport-gtk.py:352 ../kde/apport-kde.py:278
msgid "Ignore future problems of this type"
msgstr "Ігнорувати такі проблеми у майбутньому"

#: ../gtk/apport-gtk.py:670 ../kde/apport-kde.py:327
msgid "Hide Details"
msgstr ""

#: ../gtk/apport-gtk.ui.h:1 ../kde/apport-kde.py:552 ../kde/apport-kde.py:595
msgid "Apport"
msgstr ""

#: ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Скасувати"

#: ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "Гаразд"

#: ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr ""

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Вибачте, сталася внутрішня помилка.</b></big>"

#: ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Ігнорувати подальші збої у цій версії програми"

#: ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Збір інформації про помилку</b></big>"

#: ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Проводиться збір інформації, яка може допомогти розробникам виправити цю "
"помилку."

#: ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Передача інформації про помилку</b></big>"

#: ../gtk/apport-gtk.ui.h:19 ../kde/apport-kde.py:513
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Зібрана інформація пересилається до системи обліку помилок. Це може тривати "
"декілька хвилин."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Пошкодженя файлу Apport"

#: ../kde/apport-kde.py:261
msgid "Leave Closed"
msgstr "Залишити закритим"

#: ../kde/apport-kde.py:262 ../kde/apport-kde.py:432
msgid "Relaunch"
msgstr ""

#: ../kde/apport-kde.py:355
msgid "Username:"
msgstr ""

#: ../kde/apport-kde.py:356
msgid "Password:"
msgstr ""

#: ../kde/apport-kde.py:461
msgid "Collecting Problem Information"
msgstr ""

#: ../kde/apport-kde.py:464
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Зібрані дані можна надіслати розробникам з метою покращення програми. Ви "
"можете витратити на це декілька хвилин."

#: ../kde/apport-kde.py:510
msgid "Uploading Problem Information"
msgstr ""
