# Chinese (China) translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-12-07 16:35+0100\n"
"PO-Revision-Date: 2022-10-10 02:46+0000\n"
"Last-Translator: Luke Luo <Unknown>\n"
"Language-Team: Chinese (China) <zh_CN@li.org>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2022-12-07 14:36+0000\n"
"X-Generator: Launchpad (build 41e7553f8097ce3a683f90e835708cbe7bf0006c)\n"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "收集系统信息"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr "为此问题报告收集系统信息需要授权"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "系统问题报告"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr "请输入您的密码以查看系统程序问题报告。"

#: ../apport/ui.py:165
msgid "This package does not seem to be installed correctly"
msgstr "该软件包似乎没有被正确安装"

#: ../apport/ui.py:175
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""
"%s 软件包似乎不是官方版本。请在更新可用包索引后重试，如果仍然不能工作，请移除"
"这些第三方软件包后再试。"

#: ../apport/ui.py:205
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"您安装了一些过时的软件包版本。请升级以下软件包，并检查问题是否仍然发生：\n"
"\n"
"%s"

#: ../apport/ui.py:359
msgid "unknown program"
msgstr "未知程序"

#: ../apport/ui.py:362
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "对不起，%s 程序异常退出"

#: ../apport/ui.py:365 ../apport/ui.py:1899
#, python-format
msgid "Problem in %s"
msgstr "%s 中的问题"

#: ../apport/ui.py:370
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr "您的计算机剩余空间不足，程序无法自动诊断问题并向开发者发送问题报告。"

#: ../apport/ui.py:430 ../apport/ui.py:448 ../apport/ui.py:621
#: ../apport/ui.py:630 ../apport/ui.py:867 ../apport/ui.py:1677
#: ../apport/ui.py:1860 ../apport/ui.py:1865
msgid "Invalid problem report"
msgstr "无效的问题报告"

#: ../apport/ui.py:431
msgid "You are not allowed to access this problem report."
msgstr "您没有访问这个问题报告的权限。"

#: ../apport/ui.py:439
msgid "Error"
msgstr "错误"

#: ../apport/ui.py:441
msgid "There is not enough disk space available to process this report."
msgstr "没有足够的磁盘空间来处理报告。"

#: ../apport/ui.py:479
msgid "No PID specified"
msgstr "没有指定 PID"

#: ../apport/ui.py:481
msgid "You need to specify a PID. See --help for more information."
msgstr "你需要指定一个 PID。获取更多信息请使用 --help 参数。"

#: ../apport/ui.py:492 ../apport/ui.py:597
msgid "Invalid PID"
msgstr "无效的 PID"

#: ../apport/ui.py:493
msgid "The specified process ID does not exist."
msgstr "指定的进程ID不存在。"

#: ../apport/ui.py:498
msgid "Not your PID"
msgstr "不是您的 PID"

#: ../apport/ui.py:499
msgid "The specified process ID does not belong to you."
msgstr "这个指定的进程 ID 不属于您。"

#: ../apport/ui.py:554
msgid "No package specified"
msgstr "没有指定软件包"

#: ../apport/ui.py:556
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr "您需要指定一个软件包或者 PID。使用 --help 选项来获取更多信息。"

#: ../apport/ui.py:584
msgid "Permission denied"
msgstr "拒绝访问"

#: ../apport/ui.py:586
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr "指定的进程只能以进程的所有者或 root 身份运行。"

#: ../apport/ui.py:599
msgid "The specified process ID does not belong to a program."
msgstr "指定的进程 ID 不属于一个程序。"

#: ../apport/ui.py:623
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "症状脚本 %s 没有划定受影响的包"

#: ../apport/ui.py:631
#, python-format
msgid "Package %s does not exist"
msgstr "软件包 %s 不存在"

#: ../apport/ui.py:660 ../apport/ui.py:872 ../apport/ui.py:905
#: ../apport/ui.py:915
msgid "Cannot create report"
msgstr "无法创建报告"

#: ../apport/ui.py:675 ../apport/ui.py:734 ../apport/ui.py:752
msgid "Updating problem report"
msgstr "更新问题报告"

#: ../apport/ui.py:677
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"您不是该问题报告的报告者或订阅者，或者该报告被视为重复或已经关闭。\n"
"请使用 apport-bug 新建一份报告。"

#: ../apport/ui.py:689
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"您并不是这个问题报告的报告者。相对而言，标记一个重复的错误远比迁移您的评论和"
"附件到新的错误报告容易得多。\n"
"因此，我们建议您使用 apport-bug 来提交新的错误报告，并在当前报告中对您新提交"
"的报告进行评论。\n"
"您确定要继续么？"

#: ../apport/ui.py:735 ../apport/ui.py:753
msgid "No additional information collected."
msgstr "未收集更多信息。"

#: ../apport/ui.py:816
msgid "What kind of problem do you want to report?"
msgstr "您想报告什么类型的问题？"

#: ../apport/ui.py:837
msgid "Unknown symptom"
msgstr "未知症状"

#: ../apport/ui.py:838
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "症状 %s 未知。"

#: ../apport/ui.py:874
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""
"窗口选项不能在Wayland上使用。\n"
"\n"
"请找到该窗口的进程ID，然后运行’ubuntu-bug <进程ID>‘。\n"
"\n"
"可以通过运行System Monitor应用程序找到进程ID。在Processes选项卡中，滚动直到找"
"到正确的应用程序。进程ID是ID列中列出的编号。"

#: ../apport/ui.py:890
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr "在关闭这个消息只后，请点击要报告问题的程序窗口。"

#: ../apport/ui.py:907 ../apport/ui.py:916
msgid "xprop failed to determine process ID of the window"
msgstr "xprop 无法确定窗口的进程 ID"

#: ../apport/ui.py:931
#, python-format
msgid "%(prog)s <report number>"
msgstr ""

#: ../apport/ui.py:932
msgid "Specify package name."
msgstr "请指定包的名称。"

#: ../apport/ui.py:938 ../apport/ui.py:1070
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "向报告中添加额外的标记，可多次指定。"

#: ../apport/ui.py:976
#, python-format
msgid ""
"%(prog)s [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:987
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"以填写 bug 模式启动。需要 --package 和可选的 --pid 参数，或单独使用 --pid 参"
"数。如果二者均未给出，将显示一系列症状供选择。"

#: ../apport/ui.py:996
msgid "Click a window as a target for filing a problem report."
msgstr "点击一个窗口作为提交问题报告的目标。"

#: ../apport/ui.py:1005
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "启动错误更新模式。可以使用选项 --package 来指定软件包。"

#: ../apport/ui.py:1014
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr "针对某个症状报告 bug。"

#: ../apport/ui.py:1023
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"--file-bug 模式中指定软件包名。如果指定了 --pid，则是可选的。(如果只给定软件"
"包名这一个参数则为必需。)"

#: ../apport/ui.py:1034
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"在 --file-bug 模式中指定运行的程序。如果指定，该问题报告将包含更多的信息。(默"
"认指定 pid 作为唯一参数。)"

#: ../apport/ui.py:1042
msgid "The provided pid is a hanging application."
msgstr "此进程号的程序是挂起的。"

#: ../apport/ui.py:1050
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"从给定的 .apport 或者  .crash 文件，而不是从正在处理的 %s 中汇报崩溃。(如果文"
"件只给定了参数时实现。)"

#: ../apport/ui.py:1060
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"在提交报告过程中，将收集到的信息保存到要报告的文件中。该文件可用于稍后在另一"
"台机器上提交。"

#: ../apport/ui.py:1078
msgid "Print the Apport version number."
msgstr "输出 Apport 版本号"

#: ../apport/ui.py:1240
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr "这将在终端窗口中启动 apport-retrace，以检查此崩溃。"

#: ../apport/ui.py:1244
msgid "Run gdb session"
msgstr "运行 gdb 会话"

#: ../apport/ui.py:1245
msgid "Run gdb session without downloading debug symbols"
msgstr "不下载调试符号的情况下运行 gdb 会话"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1247
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "利用全符号的堆栈跟踪更新 %s"

#: ../apport/ui.py:1309
msgid "Can't remember send report status settings"
msgstr "无法记取发送报告的状态设置"

#: ../apport/ui.py:1313
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr "保存崩溃报告状态失败， 无法设置自动或永不报告模式。"

#: ../apport/ui.py:1396 ../apport/ui.py:1409
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "这一问题报告适用于不再安装的程序。"

#: ../apport/ui.py:1433
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr "自崩溃发生起已更改的程序 %s 出现问题。"

#: ../apport/ui.py:1494 ../apport/ui.py:1618 ../apport/ui.py:1869
msgid "This problem report is damaged and cannot be processed."
msgstr "该问题报告已损坏，无法处理。"

#: ../apport/ui.py:1503
msgid "This report is about a package that is not installed."
msgstr "这份报告是关于未安装软件包的信息。"

#: ../apport/ui.py:1511
msgid "An error occurred while attempting to process this problem report:"
msgstr "尝试处理此问题报告时出现错误："

#: ../apport/ui.py:1528
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr "您安装了该应用程序的两个版本，您希望针对哪个版本报告错误？"

#: ../apport/ui.py:1533
#, python-format
msgid "%s snap"
msgstr "%s snap"

#: ../apport/ui.py:1534
#, python-format
msgid "%s deb package"
msgstr "%s deb 软件包"

#: ../apport/ui.py:1575
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr "%s是由snap提供%s发布的软件。通过%s联系他们以获得帮助。"

#: ../apport/ui.py:1580
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""
"%s 是 %s 提供的一个 Snap，但没有提供联系地址。请访问 https://forum.snapcraft."
"io 以寻求帮助。"

#: ../apport/ui.py:1679
msgid "Could not determine the package or source package name."
msgstr "无法检测包或者源码包的名称。"

#: ../apport/ui.py:1704
msgid "Unable to start web browser"
msgstr "无法打开浏览器"

#: ../apport/ui.py:1705
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "无法使用浏览器打开网页 %s"

#: ../apport/ui.py:1815
msgid "Network problem"
msgstr "网络问题"

#: ../apport/ui.py:1819
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr "无法连接到崩溃数据库，请检查您的 Internet 连接。"

#: ../apport/ui.py:1851
msgid "Memory exhaustion"
msgstr "内存耗尽"

#: ../apport/ui.py:1853
msgid "Your system does not have enough memory to process this crash report."
msgstr "您的系统没有足够的内存来处理此崩溃报告。"

#: ../apport/ui.py:1904
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"无法报告问题：\n"
"\n"
"%s"

#: ../apport/ui.py:1960 ../apport/ui.py:1972
msgid "Problem already known"
msgstr "该问题为已知问题"

#: ../apport/ui.py:1962
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr "关于这个问题，之前已经有如网页所示的报告。您是否有所补充？"

#: ../apport/ui.py:1974
msgid "This problem was already reported to developers. Thank you!"
msgstr "已将此问题报告给开发人员。谢谢！"

#: ../bin/apport-cli.py:84
msgid "Press any key to continue..."
msgstr "按任意键继续…"

#: ../bin/apport-cli.py:91
msgid "What would you like to do? Your options are:"
msgstr "您想做什么？您的选择是："

#: ../bin/apport-cli.py:104
#, python-format
msgid "Please choose (%s):"
msgstr "请选择(%s)："

#: ../bin/apport-cli.py:172
#, python-format
msgid "(%i bytes)"
msgstr "(%i 字节)"

#: ../bin/apport-cli.py:174 ../gtk/apport-gtk.py:169 ../kde/apport-kde.py:406
msgid "(binary data)"
msgstr "(二进制数据)"

#: ../bin/apport-cli.py:209 ../gtk/apport-gtk.py:208 ../gtk/apport-gtk.ui.h:6
#: ../kde/apport-kde.py:199
msgid "Send problem report to the developers?"
msgstr "要向开发者发送问题报告吗？"

#: ../bin/apport-cli.py:211
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"当问题报告被发出之后，请填写\n"
"自动弹出窗口的表格。"

#: ../bin/apport-cli.py:218
#, python-format
msgid "&Send report (%s)"
msgstr "发送报告(&S)(%s)"

#: ../bin/apport-cli.py:223
msgid "&Examine locally"
msgstr "本地检查(&E)"

#: ../bin/apport-cli.py:227
msgid "&View report"
msgstr "查看报告(&V)"

#: ../bin/apport-cli.py:230
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "保存报告文件以便稍后发送或者复制到其他地方(&K)"

#: ../bin/apport-cli.py:235
msgid "Cancel and &ignore future crashes of this program version"
msgstr "终止并忽略这个版本软件以后出现的崩溃(&I)"

#: ../bin/apport-cli.py:238 ../bin/apport-cli.py:332 ../bin/apport-cli.py:366
#: ../bin/apport-cli.py:389
msgid "&Cancel"
msgstr "取消(&C)"

#: ../bin/apport-cli.py:273
msgid "Problem report file:"
msgstr "问题报告文件："

#: ../bin/apport-cli.py:279 ../bin/apport-cli.py:284
msgid "&Confirm"
msgstr "确认(&C)"

#: ../bin/apport-cli.py:283
#, python-format
msgid "Error: %s"
msgstr "错误：%s"

#: ../bin/apport-cli.py:289 ../kde/apport-kde.py:462
msgid "Collecting problem information"
msgstr "正在收集问题信息"

#: ../bin/apport-cli.py:291
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"收集到的信息将会传送到开发人员处以改进软件。\n"
"这可能会花费几分钟时间，"

#: ../bin/apport-cli.py:307 ../gtk/apport-gtk.ui.h:17 ../kde/apport-kde.py:511
msgid "Uploading problem information"
msgstr "上传问题信息"

#: ../bin/apport-cli.py:309
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"收集到的信息正在被发送到错误跟踪系统。\n"
"这可能要花费几分钟时间。"

#: ../bin/apport-cli.py:365
msgid "&Done"
msgstr "完成(&D)"

#: ../bin/apport-cli.py:371
msgid "none"
msgstr "无"

#: ../bin/apport-cli.py:373
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "已选择：%s。 多重选择："

#: ../bin/apport-cli.py:390
msgid "Choices:"
msgstr "选择："

#: ../bin/apport-cli.py:404
msgid "Path to file (Enter to cancel):"
msgstr "文件的路径(回车取消)："

#: ../bin/apport-cli.py:410
msgid "File does not exist."
msgstr "文件不存在。"

#: ../bin/apport-cli.py:412
msgid "This is a directory."
msgstr "这是一个目录。"

#: ../bin/apport-cli.py:418
msgid "To continue, you must visit the following URL:"
msgstr "要继续，您必须访问下面这个网址："

#: ../bin/apport-cli.py:421
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr "您现在可以启动一个浏览器，或者复制这个网址到另外一个电脑的浏览器。"

#: ../bin/apport-cli.py:427
msgid "Launch a browser now"
msgstr "现在启动一个浏览器"

#: ../bin/apport-cli.py:443
msgid "No pending crash reports. Try --help for more information."
msgstr "没有已知的崩溃报告，尝试 --help 以获得更多信息。"

#: ../bin/apport-retrace.py:44
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "不把新的痕迹写入到报告，但是把它们写入到标准输出。"

#: ../bin/apport-retrace.py:53
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr "启动一个交互式的 gdb 进程并载入提交的崩溃信息 (-o 不重新生成报告)"

#: ../bin/apport-retrace.py:62
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr "将更改过的报告写入指定文件而非改变原始报告"

#: ../bin/apport-retrace.py:72
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "生成栈回溯后将内核转储从报告中删除"

#: ../bin/apport-retrace.py:80
msgid "Override report's CoreFile"
msgstr "覆盖报告核心文件"

#: ../bin/apport-retrace.py:86
msgid "Override report's ExecutablePath"
msgstr "覆盖报告执行路径"

#: ../bin/apport-retrace.py:92
msgid "Override report's ProcMaps"
msgstr "覆盖报告的进程表"

#: ../bin/apport-retrace.py:98
msgid "Rebuild report's Package information"
msgstr "重建报告的包信息"

#: ../bin/apport-retrace.py:105
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"构建临时沙盒，以及下载/安装必要的软件包和调试符号；如果没有该选项，则会假设该"
"系统中已安装了必要的软件包和调试符号。此参数指向该打包系统配置库目录；如果指"
"定 \"system\"，则其将使用系统配置文件，但之后，其将只能够追溯当前正在运行的版"
"本上发生的崩溃。"

#: ../bin/apport-retrace.py:119
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""
"生成另一个临时沙盒，在其中安装报告所述版本的 gdb 和它的依赖项，而不使用您现有"
"版本的 gdb。"

#: ../bin/apport-retrace.py:129
msgid "Report download/install progress when installing packages into sandbox"
msgstr "在将软件包安装到沙盒中时，报告下载和安装的进度"

#: ../bin/apport-retrace.py:136
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "为进行批量操作，请预先设置时间戳，以记录消息"

#: ../bin/apport-retrace.py:142
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr "根据报告中指定的来源创建并使用第三方软件仓库"

#: ../bin/apport-retrace.py:150
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "下载到沙盒中软件包的缓存目录"

#: ../bin/apport-retrace.py:156
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr "用于解压包目录。以后运行将假设任何已下载的包被提取到这个沙盒。"

#: ../bin/apport-retrace.py:167 ../bin/apport-valgrind.py:97
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr "将其他软件包安装到沙盒(可多次加以指定)中"

#: ../bin/apport-retrace.py:174
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"包含崩溃数据库访问信息文件之路径。此项将用于为特定崩溃代码上传堆栈的回溯调试"
"信息(除非用户指定 -g, -o 或 -s)"

#: ../bin/apport-retrace.py:184
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr "显示返回的堆栈信息，并询求确认是否将其发送至崩溃数据库。"

#: ../bin/apport-retrace.py:192
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr "SQLite 数据库路径重复(默认：不重复检查)"

#: ../bin/apport-retrace.py:200
msgid "Do not add StacktraceSource to the report."
msgstr "不要将 StacktraceSource 附加到报告中。"

#: ../bin/apport-retrace.py:213
msgid "You cannot use -C without -S. Stopping."
msgstr "您不能在未指定 -S 选项的情况下使用 -C 选项，停止。"

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:243
msgid "OK to send these as attachments? [y/n]"
msgstr "确定以附件形式发送这些？[y/n]"

#: ../bin/apport-unpack.py:29
#, python-format
msgid "%(prog)s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:31
msgid "Report file to unpack"
msgstr "要解压的报告文件"

#: ../bin/apport-unpack.py:33
msgid "directory to unpack report to"
msgstr "存放解压后报告的文件夹"

#: ../bin/apport-unpack.py:59
msgid "Destination directory exists and is not empty."
msgstr "目标目录存在且不为空。"

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "更多细节请查看 man 手册。"

#: ../bin/apport-valgrind.py:46
msgid "specify the log file name produced by valgrind"
msgstr "请指定 valgrind 生成的日志文件名"

#: ../bin/apport-valgrind.py:52
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr "重复使用以前创建的缓存目录 (SDIR) ，或者，如果它不存在，则创建它"

#: ../bin/apport-valgrind.py:60
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr "不创建或重用额外的调试符号的沙箱目录，仅依靠安装调试符号。"

#: ../bin/apport-valgrind.py:69
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr "重复使用以前创建的缓存目录(CDIR)，或者，如果它不存在，则创建它"

#: ../bin/apport-valgrind.py:78
msgid "report download/install progress when installing packages into sandbox"
msgstr "安装包进入沙盒时报告下载/安装进度"

#: ../bin/apport-valgrind.py:86
msgid ""
"the executable that is run under valgrind's memcheck tool for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:129
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "错误：%s 不是可执行文件，停止。"

#: ../data/apportcheckresume.py:68
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr "发生于之前的挂起时，并且使系统午饭正常恢复。"

#: ../data/apportcheckresume.py:73
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr "发生于之前的休眠时，并且使系统午饭正常恢复。"

#: ../data/apportcheckresume.py:81
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr "这个恢复过程已经非常接近尾声，将正常结束。"

#: ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr "您的系统现在可能变得不稳定，可能需要重新启动。"

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr "提交一份问题报告…"

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "向开发者报告一个故障"

#: ../gtk/apport-gtk.py:185
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "对不起，应用程序 %s 意外停止。"

#: ../gtk/apport-gtk.py:188
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "对不起，%s 已意外关闭。"

#: ../gtk/apport-gtk.py:193 ../kde/apport-kde.py:214 ../kde/apport-kde.py:266
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "对不起，%s 出现了内部错误。"

#: ../gtk/apport-gtk.py:216 ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:207
msgid "Send"
msgstr "发送"

#: ../gtk/apport-gtk.py:234 ../gtk/apport-gtk.py:666 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:330
msgid "Show Details"
msgstr "显示详细信息"

#: ../gtk/apport-gtk.py:247 ../kde/apport-kde.py:258 ../kde/apport-kde.py:276
msgid "Continue"
msgstr "继续"

#: ../gtk/apport-gtk.py:271
#, python-format
msgid "The application %s has stopped responding."
msgstr "应用程序 %s 停止响应。"

#: ../gtk/apport-gtk.py:275
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "程序 %s 停止响应。"

#: ../gtk/apport-gtk.py:292 ../kde/apport-kde.py:222
#, python-format
msgid "Package: %s"
msgstr "软件包：%s"

#: ../gtk/apport-gtk.py:298 ../kde/apport-kde.py:229
msgid "Sorry, a problem occurred while installing software."
msgstr "对不起，安装软件时出现问题。"

#: ../gtk/apport-gtk.py:310 ../gtk/apport-gtk.py:334 ../kde/apport-kde.py:238
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "应用程序 %s 发生内部错误。"

#: ../gtk/apport-gtk.py:316 ../kde/apport-kde.py:245
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "应用程序 %s 已意外关闭。"

#: ../gtk/apport-gtk.py:347 ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:271
msgid "If you notice further problems, try restarting the computer."
msgstr "如果您注意到更多问题，请尝试重新启动计算机。"

#: ../gtk/apport-gtk.py:352 ../kde/apport-kde.py:278
msgid "Ignore future problems of this type"
msgstr "以后忽略此类错误"

#: ../gtk/apport-gtk.py:670 ../kde/apport-kde.py:327
msgid "Hide Details"
msgstr "隐藏详细信息"

#: ../gtk/apport-gtk.ui.h:1 ../kde/apport-kde.py:552 ../kde/apport-kde.py:595
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "取消"

#: ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "确定"

#: ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "崩溃报告"

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>对不起，发生内部错误。</b></big>"

#: ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "请确保您能记住它"

#: ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "以后忽略此版本程序的问题"

#: ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "重新启动此应用程序"

#: ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "本地检查(_E)"

#: ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "不发送"

#: ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>正在收集问题信息</b></big>"

#: ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr "正在收集信息，这些信息将会帮助开发人员修复您报告的问题。"

#: ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>正在上传问题信息</b></big>"

#: ../gtk/apport-gtk.ui.h:19 ../kde/apport-kde.py:513
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr "所收集的信息正在发送到缺陷跟踪系统。这可能需要几分钟。"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport 崩溃文件"

#: ../kde/apport-kde.py:261
msgid "Leave Closed"
msgstr "保持关闭状态"

#: ../kde/apport-kde.py:262 ../kde/apport-kde.py:432
msgid "Relaunch"
msgstr "重新启动程序"

#: ../kde/apport-kde.py:355
msgid "Username:"
msgstr "用户名："

#: ../kde/apport-kde.py:356
msgid "Password:"
msgstr "密码："

#: ../kde/apport-kde.py:461
msgid "Collecting Problem Information"
msgstr "正在收集问题信息"

#: ../kde/apport-kde.py:464
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr "收集到的信息可以发送给开发者来改进程序。这可能要花费几分钟的时间。"

#: ../kde/apport-kde.py:510
msgid "Uploading Problem Information"
msgstr "上传问题信息"
